apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: revenexx-python
  title: Revenexx Python
  description: "Revenexx Python SDK for server-side applications."
  annotations:
    github.com/project-slug: revenexx-sdks/python
    backstage.io/techdocs-ref: url:https://github.com/revenexx-sdks/python/tree/main/
  links:
    - url: https://github.com/revenexx-sdks/python
      title: GitHub Repository
      icon: github
spec:
  type: library
  lifecycle: production
  owner: group:default/developer-experience
  system: revenue-cloud
