from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel

class AssetFamilies(AppwriteModel):
    """
    

    Attributes
    ----------
    code : Optional[str]
        The asset family&#039;s stable identifier — a class of media with one shared shape. Unique per tenant.
    created_at : Optional[str]
        When the row was created. Server-set — it is not part of any request body.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    labels : Optional[Dict[str, Any]]
        What the asset family is called, per language tag.
    naming_convention : Optional[Dict[str, Any]]
        How a file of this family is named, so an import can bind a file to a product without a mapping table. `source` is the product value the file name is built from, `pattern` how it is assembled, `allowed_extensions` what may be uploaded.
    updated_at : Optional[str]
        When the row was last written. Server-set — it is not part of any request body.
    """
    code: Optional[str] = Field(default=None, alias='code')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    id: Optional[str] = Field(default=None, alias='id')
    labels: Optional[Dict[str, Any]] = Field(default=None, alias='labels')
    naming_convention: Optional[Dict[str, Any]] = Field(default=None, alias='naming_convention')
    updated_at: Optional[str] = Field(default=None, alias='updated_at')
