from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel

class AssociationTypes(AppwriteModel):
    """
    

    Attributes
    ----------
    code : Optional[str]
        The kind of relation between two products. Unique per tenant.
    created_at : Optional[str]
        When the row was created. Server-set — it is not part of any request body.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    is_quantified : Optional[bool]
        Declares that a relation of this kind carries a quantity — a bundle, a bill of materials. `product_associations.quantity` is where that number goes, and it is meaningless without this flag.
    is_two_way : Optional[bool]
        Declares the relation symmetric — an accessory of A is an accessory of B. It is a declaration a client reads: this app stores one row per direction and does not create the mirror for you.
    labels : Optional[Dict[str, Any]]
        What the relation is called in a product form, per language tag.
    """
    code: Optional[str] = Field(default=None, alias='code')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    id: Optional[str] = Field(default=None, alias='id')
    is_quantified: Optional[bool] = Field(default=None, alias='is_quantified')
    is_two_way: Optional[bool] = Field(default=None, alias='is_two_way')
    labels: Optional[Dict[str, Any]] = Field(default=None, alias='labels')
