from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel

class AttributeGroups(AppwriteModel):
    """
    

    Attributes
    ----------
    code : Optional[str]
        The group&#039;s stable identifier, and the value an `AttributeField` carries as its `group` — a SECTION of the product form, not a label. Unique per tenant and the key an import joins on.
    created_at : Optional[str]
        When the row was created. Server-set — it is not part of any request body.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    labels : Optional[Dict[str, Any]]
        The section heading a person sees, keyed by language tag. The code is never shown to an operator; a tag nobody translated falls back to the next filled one, then to English.
    position : Optional[float]
        Where this section sits in a form, ascending. Sections that tie keep the order the database returns them in.
    updated_at : Optional[str]
        When the row was last written. Server-set — it is not part of any request body.
    """
    code: Optional[str] = Field(default=None, alias='code')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    id: Optional[str] = Field(default=None, alias='id')
    labels: Optional[Dict[str, Any]] = Field(default=None, alias='labels')
    position: Optional[float] = Field(default=None, alias='position')
    updated_at: Optional[str] = Field(default=None, alias='updated_at')
