from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel

class AttributeOptions(AppwriteModel):
    """
    

    Attributes
    ----------
    attribute_id : Optional[str]
        The select / multi-select attribute these are the permitted values of. Deleting the attribute deletes its options with it.
    code : Optional[str]
        The value actually STORED in a record&#039;s `attribute_values` when this option is picked — never the label. Unique within the attribute.
    created_at : Optional[str]
        When the row was created. Server-set — it is not part of any request body.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    labels : Optional[Dict[str, Any]]
        What the option is called, per language tag. Two tenants may label the same code differently; only the code is ever written into a record.
    position : Optional[float]
        Order in the dropdown, ascending. Options that tie keep the order the database returns them in, so give every option a position if the order matters.
    swatch : Optional[Dict[str, Any]]
        A colour or texture chip for the picker. Null for an option that is not visual.
    """
    attribute_id: Optional[str] = Field(default=None, alias='attribute_id')
    code: Optional[str] = Field(default=None, alias='code')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    id: Optional[str] = Field(default=None, alias='id')
    labels: Optional[Dict[str, Any]] = Field(default=None, alias='labels')
    position: Optional[float] = Field(default=None, alias='position')
    swatch: Optional[Dict[str, Any]] = Field(default=None, alias='swatch')
