from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel

class FamilyVariants(AppwriteModel):
    """
    

    Attributes
    ----------
    axes : Optional[Dict[str, Any]]
        The attribute codes a product model splits its variants on. Two shapes are in the wild and both are read: a bare list of codes, or one entry per level, outermost first — `[{&quot;level&quot;: 1, &quot;axes&quot;: [&quot;colour&quot;]}, {&quot;level&quot;: 2, &quot;axes&quot;: [&quot;size&quot;]}]`. An attribute named here is READ-ONLY on the model and set on each variant, which is what `AttributeField.readonly_reason` reports.
    code : Optional[str]
        The variant structure&#039;s stable identifier — how this family splits, not which product it splits. Unique per tenant.
    created_at : Optional[str]
        When the row was created. Server-set — it is not part of any request body.
    family_id : Optional[str]
        The family this variant structure belongs to. A family may carry several, and a product names the one it follows through `family_variant_id`.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    labels : Optional[Dict[str, Any]]
        What the variant structure is called, per language tag.
    updated_at : Optional[str]
        When the row was last written. Server-set — it is not part of any request body.
    """
    axes: Optional[Dict[str, Any]] = Field(default=None, alias='axes')
    code: Optional[str] = Field(default=None, alias='code')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    family_id: Optional[str] = Field(default=None, alias='family_id')
    id: Optional[str] = Field(default=None, alias='id')
    labels: Optional[Dict[str, Any]] = Field(default=None, alias='labels')
    updated_at: Optional[str] = Field(default=None, alias='updated_at')
