from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel

class FamilyAttributes(AppwriteModel):
    """
    

    Attributes
    ----------
    attribute_id : Optional[str]
        The attribute the family carries. One row per (family, attribute); deleting either side deletes the link.
    created_at : Optional[str]
        When the row was created. Server-set — it is not part of any request body.
    family_id : Optional[str]
        The family this link belongs to — one side of the pair that makes an attribute part of a family&#039;s form.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    is_required : Optional[bool]
        The attribute has to carry a value for a product of this family to count as complete. `POST /products/{id}/completeness` measures exactly these and nothing else.
    position : Optional[float]
        The family&#039;s own ordering of this attribute, which overrides the attribute&#039;s default `position` in this family&#039;s form.
    required_channels : Optional[Dict[str, Any]]
        Narrows `is_required` to named channels. NULL or an empty list means required EVERYWHERE, not nowhere — that is how every required link in the wild is stored, and reading an empty list as &quot;nowhere&quot; reports a fully configured family as demanding nothing.
    """
    attribute_id: Optional[str] = Field(default=None, alias='attribute_id')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    family_id: Optional[str] = Field(default=None, alias='family_id')
    id: Optional[str] = Field(default=None, alias='id')
    is_required: Optional[bool] = Field(default=None, alias='is_required')
    position: Optional[float] = Field(default=None, alias='position')
    required_channels: Optional[Dict[str, Any]] = Field(default=None, alias='required_channels')
