from typing import Any, Dict, List, Optional, Union, cast, Generic, TypeVar, Type
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel
from .form_kit_node import FormKitNode
from .form_settings import FormSettings
from ..enums.form_status import FormStatus

T = TypeVar('T')

class Form(AppwriteModel, Generic[T]):
    """
    

    Attributes
    ----------
    created_at : Optional[str]
        When the form was first stored.
    definition : Optional[List[FormKitNode[T]]]
        The form itself: a FormKit schema, held as a flat ARRAY of nodes (it defaults to `[]`, never to an object) and rendered verbatim by the storefront.
        
        Read it as the field list. Every node carrying a non-empty `name` collects one value and writes it into a submission&#039;s `data` under exactly that name — the example below produces `{&quot;company&quot;: …, &quot;email&quot;: …, &quot;message&quot;: …}` — while `$el` content nodes and `$rxStep` step markers collect nothing. Order is render order, and a `$rxStep` marker starts a new wizard step.
        
        See the `FormKitNode` schema for what a node may carry.
    id : Optional[str]
        The form&#039;s own id, generated by the database. It is what a submission&#039;s `form_id` points at and what the Cockpit and the storefront BFF hold once they have resolved a form, so it outlives a rename of the slug.
    metadata : Optional[Dict[str, Any]]
        Free-form metadata on the FORM, which this app neither reads nor writes: yours to key however an integration needs, stored and returned verbatim. (The metadata this app does write is on a SUBMISSION — see `FormSubmissionMetadata`.)
    name : Optional[str]
        What this form is called in the Cockpit&#039;s form list. Operator-facing only — the storefront never renders it, so renaming a form breaks no page.
    settings : Optional[FormSettings[T]]
        Everything about a form that is not a field: what the storefront renders around the inputs, what happens after a successful submit, and who is told about it. Open jsonb, so an unknown key is stored and handed back rather than refused — the keys below are the ones something actually READS, and each says which reader that is. Null on a form nobody has configured, which is not an error: every one of these has a fallback.
    slug : Optional[str]
        URL-safe identifier, unique per tenant. This is the name a storefront resolves a form by (`GET /v1/forms?slug=contact&amp;status=live&amp;limit=1`), so it is part of the page&#039;s contract: changing it changes which form a page renders. Lower-case letters, digits and inner hyphens.
    status : Optional[FormStatus]
        Lifecycle. `draft` while it is being built; `live` once the storefront may render it — the cover BFF resolves live forms only, so a draft is a 404 on the storefront and never a broken page; `archived` for a form that is kept for its submissions but no longer offered. Default &#039;draft&#039;.
    tenant_id : Optional[str]
        The tenant this row belongs to — the store slug, not an id. Set by the platform from the authenticated context, never by a caller; a write that carries it is ignored, and no request can read another tenant&#039;s rows by sending a different one.
    updated_at : Optional[str]
        When the form was last written. This app stamps it on every PUT, so it is the timestamp an editor sorts by.
    """
    created_at: Optional[str] = Field(default=None, alias='created_at')
    definition: Optional[List[FormKitNode[T]]] = Field(default=None, alias='definition')
    id: Optional[str] = Field(default=None, alias='id')
    metadata: Optional[Dict[str, Any]] = Field(default=None, alias='metadata')
    name: Optional[str] = Field(default=None, alias='name')
    settings: Optional[FormSettings[T]] = Field(default=None, alias='settings')
    slug: Optional[str] = Field(default=None, alias='slug')
    status: Optional[FormStatus] = Field(default=None, alias='status')
    tenant_id: Optional[str] = Field(default=None, alias='tenant_id')
    updated_at: Optional[str] = Field(default=None, alias='updated_at')

    @classmethod
    def with_data(cls, data: Dict[str, Any], model_type: Type[T] = dict) -> 'Form[T]':
        """Create Form instance with typed data."""
        instance = cls.model_validate(data)
        if 'definition' in data and data['definition'] is not None:
            instance.definition = [
                FormKitNode.with_data(row, model_type) 
                for row in data['definition']
            ]
        if 'settings' in data and data['settings'] is not None:
            instance.settings = FormSettings.with_data(
                data['settings'], model_type
            )
        return instance
