from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel

class MeasurementFamilies(AppwriteModel):
    """
    

    Attributes
    ----------
    code : Optional[str]
        The measurement family&#039;s stable identifier. A `measure` attribute names one and then offers that family&#039;s units.
    created_at : Optional[str]
        When the row was created. Server-set — it is not part of any request body.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    labels : Optional[Dict[str, Any]]
        What the measurement family is called, per language tag.
    standard_unit : Optional[str]
        The unit every value of this family is converted to before it is compared or sorted — the unit each `convert_factor` is relative to.
    units : Optional[Dict[str, Any]]
        The units this family offers. `convert_factor` multiplies a value into `standard_unit`, so a gram is 0.001 kilograms; `symbol` is what a form prints next to the number.
    updated_at : Optional[str]
        When the row was last written. Server-set — it is not part of any request body.
    """
    code: Optional[str] = Field(default=None, alias='code')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    id: Optional[str] = Field(default=None, alias='id')
    labels: Optional[Dict[str, Any]] = Field(default=None, alias='labels')
    standard_unit: Optional[str] = Field(default=None, alias='standard_unit')
    units: Optional[Dict[str, Any]] = Field(default=None, alias='units')
    updated_at: Optional[str] = Field(default=None, alias='updated_at')
