from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel
from .order_list_item import OrderListItem

class OrderListWithItems(AppwriteModel):
    """
    

    Attributes
    ----------
    created_at : Optional[str]
        When the list was created.
    id : Optional[str]
        The list, by id. Generated by the database and the only way to address it — every /orderlists/{id} route takes this uuid.
    items : Optional[List[OrderListItem]]
        Every position of the list, in `position` order. Returned inline because a list without its positions is not a list — the nested routes exist to CHANGE them, not to read them one page at a time.
    kind : Optional[str]
        What the list is FOR — the `code` of one of the tenant&#039;s own kinds (GET /orderlists/kinds). Nothing in this app branches on it: it groups and filters lists, it does not change how positions are stored or how a conversion runs. A merchant may add their own (reagent lists, sample lists) without a release of this app.
    metadata : Optional[Dict[str, Any]]
        Free-form data the tenant keeps on the list — an ERP requisition number, a department, whatever an integration needs to recognise the list again. Never read by this app, and never merged: a write replaces the whole document.
    name : Optional[str]
        What the buyer calls this list. Free text, at least one character, and not unique: two contacts may both keep a &quot;Weekly office supplies&quot;. It is also the name a NEW cart gets when POST /orderlists/{id}/cart creates one.
    organization_id : Optional[str]
        The organization the sharing is scoped to. Null means the list can only ever be the owner&#039;s own: `shared` is meaningless without it, because there is no set of people to share with. It is also what the order conversion hands the orders app as the buying organization.
    owner_id : Optional[str]
        The contact who owns the list. Ownership IS the authorization here: a caller the gateway resolved to a contact sees their own lists plus their organization&#039;s shared ones, and may write only their own — unless `shared_lists_editable` opens a shared list to the whole owning organization. Set once at create; no route moves a list to another owner.
    owner_name : Optional[str]
        The owner&#039;s display name as it stood when the list was created — a snapshot, so renaming the contact does not rewrite it. Carried so a shared list can say whose it is without a call to the contacts app.
    public : Optional[bool]
        Dead column: what `shared` was called before the 2026-06-20 rename (`public` is a reserved word in most SDK target languages). Nothing reads or writes it, so it is `false` on every list written since; it is still returned only because the additive provisioner never dropped the column. Read `shared` — this field says nothing about who may see the list.
    shared : Optional[bool]
        Whether the OWNING ORGANIZATION may see this list. False — the default — keeps it private to `owner_id`, and a foreign private list answers 404 rather than 403, so an outsider learns nothing from the difference. True lets every contact of `organization_id` READ it, and write it only where the tenant turned on the `shared_lists_editable` setting. A list with no `organization_id` shares with nobody however this is set.
    tenant_id : Optional[str]
        The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    updated_at : Optional[str]
        When the list or ANY of its positions last changed — adding, updating or removing a position touches the list — so this is the timestamp a &quot;recently used&quot; sort should read. It is also the default sort of GET /orderlists (`updated_at.desc`).
    """
    created_at: Optional[str] = Field(default=None, alias='created_at')
    id: Optional[str] = Field(default=None, alias='id')
    items: Optional[List[OrderListItem]] = Field(default=None, alias='items')
    kind: Optional[str] = Field(default=None, alias='kind')
    metadata: Optional[Dict[str, Any]] = Field(default=None, alias='metadata')
    name: Optional[str] = Field(default=None, alias='name')
    organization_id: Optional[str] = Field(default=None, alias='organization_id')
    owner_id: Optional[str] = Field(default=None, alias='owner_id')
    owner_name: Optional[str] = Field(default=None, alias='owner_name')
    public: Optional[bool] = Field(default=None, alias='public')
    shared: Optional[bool] = Field(default=None, alias='shared')
    tenant_id: Optional[str] = Field(default=None, alias='tenant_id')
    updated_at: Optional[str] = Field(default=None, alias='updated_at')
