from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel
from ..enums.order_list_kind_row_tone import OrderListKindRowTone

class OrderListKindRow(AppwriteModel):
    """
    

    Attributes
    ----------
    code : Optional[str]
        What `lists.kind` stores. Lowercase, immutable once created — renaming it would orphan every list that carries it, so a merchant who wants a different code creates a new kind and moves the lists over.
    created_at : Optional[str]
        When the kind was created — the install for a seeded one.
    description : Optional[str]
        What this kind is FOR, in the tenant&#039;s own words — the sentence a select shows underneath the title. `descriptions` carries the localized forms. Same caveat as `title`: a kind seeded before 0.15.0 may hold a serialized locale map here (PE-450).
    descriptions : Optional[Dict[str, Any]]
        Localized descriptions, keyed by language tag. Same fallback as `labels`: `description` is what a reader gets when their tag is missing.
    id : Optional[str]
        The kind, by id. Generated by the database and what every /orderlists/kinds/{id} route addresses — the `code` is the identity a LIST carries, the id is the identity a route takes.
    is_default : Optional[bool]
        The kind a list created without one gets. Exactly one row carries it — promoting a kind demotes the previous holder — and the market-scoped `default_kind` setting still wins where a tenant set it.
    is_system : Optional[bool]
        Seeded on install rather than created by the merchant. It changes nothing about what may be done to the row: a system kind is still renameable, still retirable, and still deletable once no list carries it.
    labels : Optional[Dict[str, Any]]
        Localized titles, keyed by language tag. `title` is what a reader gets when their tag is missing, so this only ever adds languages — it never replaces the plain one.
    position : Optional[float]
        Where this kind sits in a select, ascending. Ties fall back to the code, so the order is stable.
    tenant_id : Optional[str]
        The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    title : Optional[str]
        What a person reads, in the tenant&#039;s own words. `labels` carries the localized forms. Kinds seeded before 0.15.0 hold a serialized locale map here instead — the seed wrote its `{en, de}` map into this `text` column and left `labels` null, and Postgres stores such a map as its JSON text rather than refusing it (PE-450). Those rows are not repaired by the fix; a repair is a data change.
    tone : Optional[OrderListKindRowTone]
        Semantic badge colour. The client owns what each tone looks like; the kind only says what the value MEANS.
    updated_at : Optional[str]
        When the kind was last written.
    """
    code: Optional[str] = Field(default=None, alias='code')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    description: Optional[str] = Field(default=None, alias='description')
    descriptions: Optional[Dict[str, Any]] = Field(default=None, alias='descriptions')
    id: Optional[str] = Field(default=None, alias='id')
    is_default: Optional[bool] = Field(default=None, alias='is_default')
    is_system: Optional[bool] = Field(default=None, alias='is_system')
    labels: Optional[Dict[str, Any]] = Field(default=None, alias='labels')
    position: Optional[float] = Field(default=None, alias='position')
    tenant_id: Optional[str] = Field(default=None, alias='tenant_id')
    title: Optional[str] = Field(default=None, alias='title')
    tone: Optional[OrderListKindRowTone] = Field(default=None, alias='tone')
    updated_at: Optional[str] = Field(default=None, alias='updated_at')
