from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel

class ProductAssociations(AppwriteModel):
    """
    

    Attributes
    ----------
    association_type_id : Optional[str]
        Which kind of relation this is — the `association_types` row.
    created_at : Optional[str]
        When the row was created. Server-set — it is not part of any request body.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    position : Optional[float]
        Order in which the targets are shown, ascending.
    product_id : Optional[str]
        The product the relation starts at — the one whose detail page shows it.
    quantity : Optional[float]
        How many of the target belong to the source — the 4 in &quot;this bundle contains 4 casters&quot;. Only meaningful when the association type carries `is_quantified`; null on an ordinary cross-sell.
    target_product_id : Optional[str]
        The product the relation points at — the accessory, the spare part, the cross-sell.
    """
    association_type_id: Optional[str] = Field(default=None, alias='association_type_id')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    id: Optional[str] = Field(default=None, alias='id')
    position: Optional[float] = Field(default=None, alias='position')
    product_id: Optional[str] = Field(default=None, alias='product_id')
    quantity: Optional[float] = Field(default=None, alias='quantity')
    target_product_id: Optional[str] = Field(default=None, alias='target_product_id')
