from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel

class ProductCategories(AppwriteModel):
    """
    

    Attributes
    ----------
    category_id : Optional[str]
        The category it is filed into. One row per (product, category), whichever way it got there.
    created_at : Optional[str]
        When the row was created. Server-set — it is not part of any request body.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    position : Optional[float]
        Sort order of this product inside the category.
    product_id : Optional[str]
        The product filed into the category. Deleting the product deletes the membership with it.
    source : Optional[str]
        How the membership came about: &#039;manual&#039; is hand-picked, &#039;rule&#039; was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass.
    """
    category_id: Optional[str] = Field(default=None, alias='category_id')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    id: Optional[str] = Field(default=None, alias='id')
    position: Optional[float] = Field(default=None, alias='position')
    product_id: Optional[str] = Field(default=None, alias='product_id')
    source: Optional[str] = Field(default=None, alias='source')
