from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel

class ReferenceEntities(AppwriteModel):
    """
    

    Attributes
    ----------
    code : Optional[str]
        The entity&#039;s stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.
    created_at : Optional[str]
        When the row was created. Server-set — it is not part of any request body.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    image : Optional[str]
        A delivery path or URL for the entity&#039;s own icon. Cosmetic — nothing in this app resolves it.
    labels : Optional[Dict[str, Any]]
        What the entity is called, per language tag — the heading over its record list.
    updated_at : Optional[str]
        When the row was last written. Server-set — it is not part of any request body.
    """
    code: Optional[str] = Field(default=None, alias='code')
    created_at: Optional[str] = Field(default=None, alias='created_at')
    id: Optional[str] = Field(default=None, alias='id')
    image: Optional[str] = Field(default=None, alias='image')
    labels: Optional[Dict[str, Any]] = Field(default=None, alias='labels')
    updated_at: Optional[str] = Field(default=None, alias='updated_at')
