from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel
from ..enums.reservation_status import ReservationStatus

class Reservation(AppwriteModel):
    """
    

    Attributes
    ----------
    created_at : Optional[str]
        When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
    expires_at : Optional[str]
        When this hold lapses. The sweeper — POST /inventories/reservations/sweep, and the &#039;expire-reservations&#039; schedule that runs it every 15 minutes — releases everything past this moment exactly as a cancellation would, so an abandoned checkout stops holding stock on its own. Null means the row named no deadline: it is swept on its AGE instead once `reservation_ttl_minutes` is above 0, which is what makes turning that setting on retroactive.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
    location_id : Optional[str]
        Which location is holding the goods for this order. Chosen at reserve time by the tenant&#039;s `allocation_strategy` — not by the caller, unless `ship_to.location_code` names one and the strategy is &#039;nearest&#039;.
    metadata : Optional[Dict[str, Any]]
        Free-form, and one key this app writes itself: `backordered` — how much of this hold was not covered by stock on hand when it was taken. Absent on a hold that was fully covered.
    order_ref : Optional[str]
        The order this hold belongs to. The caller supplies it — this app mints nothing — and it is the handle POST /inventories/release and POST /inventories/commit act on, so it has to be the same string the order carries elsewhere. At least one character (CHECK `length(order_ref) &gt; 0`). Not unique: an order holds one reservation per item, and they are released or committed together.
    product_id : Optional[str]
        The product being held, copied from the reserve call. Null when the item was identified by SKU.
    quantity : Optional[float]
        How much is being held, ALWAYS POSITIVE — the database CHECK is `quantity &gt; 0`, because a hold of nothing is not a hold. It is added to `stock_levels.reserved` while the status is `active` and taken off again when the hold is released, expires or is committed. The matching ledger booking carries the same number NEGATIVE (see `stock_movements.quantity`).
    sku : Optional[str]
        The article number being held, copied from the reserve call. Null when the item was identified by product id.
    status : Optional[ReservationStatus]
        Where the hold stands in the reserve → commit | release lifecycle. &#039;active&#039; — holding stock, and the ONLY status counted in `stock_levels.reserved`. &#039;committed&#039; — the order shipped, so `on_hand` and `reserved` both fell. &#039;released&#039; — the hold was given back, by POST /inventories/release or by the expiry sweeper. Both end states are final: nothing in this app moves a reservation back to active.
    tenant_id : Optional[str]
        The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    updated_at : Optional[str]
        When the hold last changed — in practice, when it moved out of `active`.
    """
    created_at: Optional[str] = Field(default=None, alias='created_at')
    expires_at: Optional[str] = Field(default=None, alias='expires_at')
    id: Optional[str] = Field(default=None, alias='id')
    location_id: Optional[str] = Field(default=None, alias='location_id')
    metadata: Optional[Dict[str, Any]] = Field(default=None, alias='metadata')
    order_ref: Optional[str] = Field(default=None, alias='order_ref')
    product_id: Optional[str] = Field(default=None, alias='product_id')
    quantity: Optional[float] = Field(default=None, alias='quantity')
    sku: Optional[str] = Field(default=None, alias='sku')
    status: Optional[ReservationStatus] = Field(default=None, alias='status')
    tenant_id: Optional[str] = Field(default=None, alias='tenant_id')
    updated_at: Optional[str] = Field(default=None, alias='updated_at')
