from typing import Any, Dict, List, Optional, Union, cast
from pydantic import Field, PrivateAttr

from .base_model import AppwriteModel
from ..enums.stock_movement_type import StockMovementType

class StockMovement(AppwriteModel):
    """
    

    Attributes
    ----------
    created_at : Optional[str]
        When the booking was written — the ledger&#039;s own clock and its natural order, which is why `?order=created_at.desc` is the feed order. There is no `updated_at`: the ledger is append-only, and a correction is another booking rather than an edit.
    id : Optional[str]
        The row&#039;s own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
    location_id : Optional[str]
        Where the booking happened. Copied from the call that caused it, not a foreign key — a movement outlives the location row it names.
    metadata : Optional[Dict[str, Any]]
        Free-form, and two keys this app writes itself: `backordered` — on a `reserve` booking, how much of the hold was not covered by stock on hand; `shortfall` — on a `shipment` booking, how much was committed that was not physically there (`on_hand` floors at 0, so the difference is recorded here instead of vanishing). Neither key is present on a booking that needed neither.
    order_ref : Optional[str]
        The order this booking belongs to, for the bookings an order causes — &#039;reserve&#039;, &#039;release&#039;, &#039;shipment&#039;, and a &#039;restock&#039; that names one. Null for a receipt or a stocktake. It is the join that reconstructs one order&#039;s whole stock history: GET /inventories/movements?order_ref=…
    product_id : Optional[str]
        The product this booking is for, copied from the call. Null when the item was identified by SKU.
    quantity : Optional[float]
        The SIGNED size of the booking — a DELTA, never a balance, and deliberately the one quantity in this app with no bound on it. `stock_levels.on_hand`/`reserved` and `reservations.quantity` each carry a CHECK; this column carries none, because the SIGN is the direction of the booking and a rule that forbade one of them would forbid half the ledger. Positive adds to what the location holds (&#039;inbound&#039;, &#039;restock&#039;, a positive &#039;adjustment&#039;); negative takes it away (&#039;shipment&#039;, a negative &#039;adjustment&#039;). &#039;reserve&#039; books the NEGATIVE of the quantity held (−5 for a hold of 5) while the reservation row itself carries +5: the movement says which way stock moved, the reservation says how much is being held. Summing this column for one (location, item) reconstructs `on_hand` — which is what makes the ledger an audit trail and not a log.
    reason : Optional[str]
        Why the booking happened, in a person&#039;s words — a delivery note number, &#039;stocktake 2026-03&#039;, &#039;damaged in transit&#039;. Whether one is owed is the `movement_reason_required` setting (&#039;none&#039; | &#039;adjustments&#039; | &#039;all&#039;), never this column, which stays nullable so the tenant that requires nothing is not forced. The expiry sweeper writes &#039;reservation expired&#039; on the releases it makes.
    sku : Optional[str]
        The article number this booking is for, copied from the call. Null when the item was identified by product id.
    tenant_id : Optional[str]
        The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    type : Optional[StockMovementType]
        What the booking records. &#039;inbound&#039; — a receipt (+on_hand). &#039;adjustment&#039; — a manual correction, the only type whose sign can go either way. &#039;reserve&#039; — a hold taken for an order (`reserved` up, `on_hand` untouched). &#039;release&#039; — a hold given back, by cancellation or by the expiry sweeper. &#039;shipment&#039; — a committed reservation leaving the building (`on_hand` and `reserved` both down). &#039;restock&#039; — a return that rejoined sellable stock. GET /inventories/vocabularies/movement-types serves these with the words a person reads for them.
    """
    created_at: Optional[str] = Field(default=None, alias='created_at')
    id: Optional[str] = Field(default=None, alias='id')
    location_id: Optional[str] = Field(default=None, alias='location_id')
    metadata: Optional[Dict[str, Any]] = Field(default=None, alias='metadata')
    order_ref: Optional[str] = Field(default=None, alias='order_ref')
    product_id: Optional[str] = Field(default=None, alias='product_id')
    quantity: Optional[float] = Field(default=None, alias='quantity')
    reason: Optional[str] = Field(default=None, alias='reason')
    sku: Optional[str] = Field(default=None, alias='sku')
    tenant_id: Optional[str] = Field(default=None, alias='tenant_id')
    type: Optional[StockMovementType] = Field(default=None, alias='type')
