from ..service import Service
from typing import Any, Dict, List, Optional, Union
from ..exception import RevenexxException
from ..utils.deprecated import deprecated
from ..enums.inventories_locations_list_type import InventoriesLocationsListType;
from ..models.error import Error;
from ..enums.location_type import LocationType;

class InventoriesLocations(Service):

    def __init__(self, client) -> None:
        super(InventoriesLocations, self).__init__(client)

    def inventories_locations_list(
        self,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        order: Optional[str] = None,
        id: Optional[str] = None,
        code: Optional[str] = None,
        name: Optional[str] = None,
        labels: Optional[str] = None,
        type: Optional[InventoriesLocationsListType] = None,
        priority: Optional[float] = None,
        enabled: Optional[bool] = None,
        address: Optional[str] = None,
        metadata: Optional[str] = None,
        created_at: Optional[str] = None,
        updated_at: Optional[str] = None
    ) -> Error:
        """
        A location is WHERE stock is kept — a warehouse, a shop floor, a supplier that dropships, or a virtual bucket for pre-orders and quarantine. It holds no quantity of its own: what is at it is a stock level. `type` is descriptive and nothing branches on it; `priority` is the number that decides which location a reservation is served from, and `enabled` decides whether it is offered at all. This is the list a `location_code` is resolved against on every stock call, so it is the first thing to read when a receipt answers "unknown location". It answers no quantities at all — how much is at a location is GET /inventories/stock?location_id=…, and what may still be sold is POST /inventories/availability. Filter `?enabled=true` for the operational subset: availability and reserve only ever look at enabled locations, so a disabled one is invisible to a shop while keeping every row that points at it.

        Parameters
        ----------
        limit : Optional[float]
            Page size (default 50, max 200). A larger value is clamped rather than refused.
        offset : Optional[float]
            Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
        order : Optional[str]
            Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.
        id : Optional[str]
            Exact-match filter on `id`. The row's own id, generated by the database.
        code : Optional[str]
            Exact-match filter on `code`. Unique per tenant, so this resolves a code a caller already holds without paging the whole list.
        name : Optional[str]
            Exact-match filter on `name`. What the place is called for an operator, in the tenant's working language.
        labels : Optional[str]
            Exact-match filter on `labels`. The location name per language tag, for a UI that has to render it in the reader's language. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
        type : Optional[InventoriesLocationsListType]
            Exact-match filter on `type`. What kind of place holds the stock. Descriptive only — sourcing order comes from `priority`.
        priority : Optional[float]
            Exact-match filter on `priority`. Sourcing order for POST /inventories/reserve while `allocation_strategy` is 'priority': the enabled locations are walked ASCENDING and the first that can cover the item wins, so a LOWER number is preferred.
        enabled : Optional[bool]
            Exact-match filter on `enabled`. Only enabled locations are ever served by availability or reserve, so `true` is the operational subset.
        address : Optional[str]
            Exact-match filter on `address`. Where the location physically is. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
        metadata : Optional[str]
            Exact-match filter on `metadata`. Free-form data the tenant keeps on the location — an ERP site number, a contact, a cut-off time. The WHOLE jsonb document is compared, serialized as JSON — this is equality, not a key lookup or a containment query, and a value that does not parse is answered 400.
        created_at : Optional[str]
            Exact-match filter on `created_at`. When the row was created.
        updated_at : Optional[str]
            Exact-match filter on `updated_at`. When the row was last written.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/inventories/locations'
        api_params = {}

        if limit is not None:
            api_params['limit'] = self._normalize_value(limit)
        if offset is not None:
            api_params['offset'] = self._normalize_value(offset)
        if order is not None:
            api_params['order'] = self._normalize_value(order)
        if id is not None:
            api_params['id'] = self._normalize_value(id)
        if code is not None:
            api_params['code'] = self._normalize_value(code)
        if name is not None:
            api_params['name'] = self._normalize_value(name)
        if labels is not None:
            api_params['labels'] = self._normalize_value(labels)
        if type is not None:
            api_params['type'] = self._normalize_value(type)
        if priority is not None:
            api_params['priority'] = self._normalize_value(priority)
        if enabled is not None:
            api_params['enabled'] = self._normalize_value(enabled)
        if address is not None:
            api_params['address'] = self._normalize_value(address)
        if metadata is not None:
            api_params['metadata'] = self._normalize_value(metadata)
        if created_at is not None:
            api_params['created_at'] = self._normalize_value(created_at)
        if updated_at is not None:
            api_params['updated_at'] = self._normalize_value(updated_at)

        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def inventories_locations_create(
        self,
        code: str,
        name: str,
        address: Optional[Dict[str, Any]] = None,
        enabled: Optional[bool] = None,
        labels: Optional[Dict[str, Any]] = None,
        metadata: Optional[Dict[str, Any]] = None,
        priority: Optional[float] = None,
        type: Optional[LocationType] = None
    ) -> Error:
        """
        Registers a new place stock can be kept, and `type` says what kind of place it is: a warehouse of your own, a store whose shop floor a click-and-collect order draws on, a dropship supplier whose stock this row only tracks, or a virtual bucket that is not a building at all — pre-orders, consignment, a quarantine shelf. A create cannot omit `code` and `name`; every other column is optional or defaulted by the database. Two rows of this tenant may not share `code` — that is the 409, and it answers an update that moves a row onto a sibling's value exactly as it answers a second insert. A new location starts EMPTY and creating one moves nothing: stock arrives through POST /inventories/receive, or is transferred by two adjustments, one negative at the old location and one positive here. Mind the two columns that are not decoration — `priority` decides where a reservation is served from before `type` ever does (nothing branches on `type`), and `enabled` defaults to true, so a location created for a warehouse that has not opened yet starts being offered by availability and reserve immediately.

        Parameters
        ----------
        code : str
            The location's stable identifier, and the name every stock call uses instead of an id: `location_code` on receive / adjust / restock / reserve, and the `default_location_code` setting. Unique per tenant, at least one character (CHECK `length(code) > 0`). Every tenant starts with `main` — POST /inventories/locations/defaults seeds it and the app.installed event runs the same seed — so `main` is the one code that resolves everywhere.
        name : str
            What the place is called for an operator, in the tenant's working language. At least one character (CHECK `length(name) > 0`). It is a label only: nothing addresses a location by name.
        address : Optional[Dict[str, Any]]
            Where the location physically is. Free-form, and one key is READ: `country`, an ISO country code, which POST /inventories/reserve compares (case-insensitively) against `ship_to.country` when `allocation_strategy` is 'nearest' — that is what stops a German order pulling from the US warehouse because it happens to sort first. The keys the cockpit form writes are `street`, `postal_code`, `city`, `country`; anything else a tenant stores is kept and ignored.
        enabled : Optional[bool]
            Whether this location takes part in stock at all. POST /inventories/availability and POST /inventories/reserve look at enabled locations and nothing else, so switching this off hides a location's stock from the storefront without deleting a row or losing a single ledger booking; its stock stays readable through GET /inventories/stock. Defaults to true.
        labels : Optional[Dict[str, Any]]
            The location name per language tag, for a UI that has to render it in the reader's language. Falls back to `name` when a tag is missing. Keys are language tags, values plain strings.
        metadata : Optional[Dict[str, Any]]
            Free-form data the tenant keeps on the location — an ERP site number, a contact, a cut-off time. No route in this app reads it; it is stored and handed back unchanged.
        priority : Optional[float]
            Sourcing order for POST /inventories/reserve while `allocation_strategy` is 'priority': the enabled locations are walked ASCENDING and the first that can cover the item wins, so a LOWER number is preferred. Locations that tie keep the order the database returns them in — give every location a distinct priority if the order matters. Defaults to 0.
        type : Optional[LocationType]
            What kind of place holds the stock. 'warehouse' — own stock, the default. 'store' — a retail floor, the stock a click-and-collect order draws on. 'dropship' — a supplier ships it and this row tracks what they say they hold. 'virtual' — a bucket that is not a building (pre-orders, consignment, a quarantine shelf). Descriptive only: sourcing order comes from `priority`, and no route in this app treats one type differently from another. Defaults to 'warehouse'.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/inventories/locations'
        api_params = {}
        if code is None:
            raise RevenexxException('Missing required parameter: "code"')

        if name is None:
            raise RevenexxException('Missing required parameter: "name"')


        api_params['address'] = self._normalize_value(address)
        api_params['code'] = self._normalize_value(code)
        if enabled is not None:
            api_params['enabled'] = self._normalize_value(enabled)
        api_params['labels'] = self._normalize_value(labels)
        api_params['metadata'] = self._normalize_value(metadata)
        api_params['name'] = self._normalize_value(name)
        if priority is not None:
            api_params['priority'] = self._normalize_value(priority)
        if type is not None:
            api_params['type'] = self._normalize_value(type)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def inventories_locations_defaults(
        self
    ) -> Dict[str, Any]:
        """
        Gives a tenant its first location, `main`, so the stock calls have somewhere to book into: `receive`, `adjust` and `restock` fall back to the `default_location_code` setting when a caller names no `location_code`, and a tenant with no location at all answers 400 on its first receipt. The platform already runs this on `app.installed`, so calling it by hand is the repair for an install that predates the event or a `main` somebody deleted. Idempotent by CODE, not by contents: a location already carrying that code is reported under `existing` and is NOT touched, so a renamed or disabled `main` stays renamed and disabled. It creates nothing else and never removes a location.

        Returns
        -------
        Dict[str, Any]
            API response as a dictionary
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/inventories/locations/defaults'
        api_params = {}

        response = self.client.call('post', api_path, {
        }, api_params)

        return response


    def inventories_locations_delete(
        self,
        id: str
    ) -> Error:
        """
        Deleting one takes every `stock_levels` row that points at it with it — the foreign key decides that, not this route. What the database does NOT clean up is everything else carrying the same id: `stock_movements.location_id` and `reservations.location_id` are plain uuid columns and not foreign keys, so those rows stay exactly where they are, pointing at a row that no longer exists, and nothing nulls the pointer. That asymmetry destroys the balances and keeps everything that refers to them, so the route REFUSES while anything still depends on the location and answers 409 with the count — taken here rather than left to whoever is about to click delete, because a client that pre-counts asks a second question whose answer disagrees the moment a receipt lands between the two calls. Two things block it. A stock row still carrying `on_hand`: the cascade would destroy recorded inventory and nothing in this app ever replays the ledger to rebuild a balance, so there is no undo. And a reservation still `active`: a promise to a customer must not outlive the row backing it — such a hold used to survive its stock row, after which /release lowered no `reserved` and still wrote its `release` booking, and /commit booked the whole quantity as a shortfall, neither of them an error. A stock row at zero does not block: it records no quantity. HISTORY never blocks, and is never deleted either — a movement is an accounting record and removing one would falsify it, so the bookings stay, naming a location that no longer resolves, BY DESIGN. A location that once had traffic and now holds nothing is exactly what a merchant closes. To get past the 409, adjust the stock to zero and release or commit the holds; where the location is merely out of service, PUT `enabled: false` keeps every row and can be undone.

        Parameters
        ----------
        id : str
            The location.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/inventories/locations/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('delete', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def inventories_locations_get(
        self,
        id: str
    ) -> Error:
        """
        A location is WHERE stock is kept — a warehouse, a shop floor, a supplier that dropships, or a virtual bucket for pre-orders and quarantine. It holds no quantity of its own: what is at it is a stock level. `type` is descriptive and nothing branches on it; `priority` is the number that decides which location a reservation is served from, and `enabled` decides whether it is offered at all. This is the route that turns an id back into a place: `location_id` is on every stock row, every ledger booking and every reservation, and none of them carries the code or the name. Reading it also answers the two questions those rows raise — whether the location is still `enabled` (a disabled one is skipped by availability and reserve while its stock stays exactly where it is) and where its `priority` puts it when the allocation strategy picks somewhere to reserve from.

        Parameters
        ----------
        id : str
            The location.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/inventories/locations/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def inventories_locations_update(
        self,
        id: str,
        address: Optional[Dict[str, Any]] = None,
        code: Optional[str] = None,
        enabled: Optional[bool] = None,
        labels: Optional[Dict[str, Any]] = None,
        metadata: Optional[Dict[str, Any]] = None,
        name: Optional[str] = None,
        priority: Optional[float] = None,
        type: Optional[LocationType] = None
    ) -> Error:
        """
        Partial update: send the fields that change. The one with consequences is `enabled` — setting it to false is how a location is taken out of service WITHOUT losing anything. Availability and reserve stop looking at it, so its stock stops being sellable, while every stock row, ledger booking and reservation that points at it survives untouched and comes back the moment it is enabled again. That is the reversible alternative to DELETE, which is not reversible at all. Changing `code` is the other sharp edge: rows keep their `location_id` so nothing moves, but every caller that names the old code in `location_code` starts getting 400 "unknown location". Two rows of this tenant may not share `code` — that is the 409, and it answers an update that moves a row onto a sibling's value exactly as it answers a second insert.

        Parameters
        ----------
        id : str
            The location.
        address : Optional[Dict[str, Any]]
            Where the location physically is. Free-form, and one key is READ: `country`, an ISO country code, which POST /inventories/reserve compares (case-insensitively) against `ship_to.country` when `allocation_strategy` is 'nearest' — that is what stops a German order pulling from the US warehouse because it happens to sort first. The keys the cockpit form writes are `street`, `postal_code`, `city`, `country`; anything else a tenant stores is kept and ignored.
        code : Optional[str]
            The location's stable identifier, and the name every stock call uses instead of an id: `location_code` on receive / adjust / restock / reserve, and the `default_location_code` setting. Unique per tenant, at least one character (CHECK `length(code) > 0`). Every tenant starts with `main` — POST /inventories/locations/defaults seeds it and the app.installed event runs the same seed — so `main` is the one code that resolves everywhere.
        enabled : Optional[bool]
            Whether this location takes part in stock at all. POST /inventories/availability and POST /inventories/reserve look at enabled locations and nothing else, so switching this off hides a location's stock from the storefront without deleting a row or losing a single ledger booking; its stock stays readable through GET /inventories/stock. Defaults to true.
        labels : Optional[Dict[str, Any]]
            The location name per language tag, for a UI that has to render it in the reader's language. Falls back to `name` when a tag is missing. Keys are language tags, values plain strings.
        metadata : Optional[Dict[str, Any]]
            Free-form data the tenant keeps on the location — an ERP site number, a contact, a cut-off time. No route in this app reads it; it is stored and handed back unchanged.
        name : Optional[str]
            What the place is called for an operator, in the tenant's working language. At least one character (CHECK `length(name) > 0`). It is a label only: nothing addresses a location by name.
        priority : Optional[float]
            Sourcing order for POST /inventories/reserve while `allocation_strategy` is 'priority': the enabled locations are walked ASCENDING and the first that can cover the item wins, so a LOWER number is preferred. Locations that tie keep the order the database returns them in — give every location a distinct priority if the order matters. Defaults to 0.
        type : Optional[LocationType]
            What kind of place holds the stock. 'warehouse' — own stock, the default. 'store' — a retail floor, the stock a click-and-collect order draws on. 'dropship' — a supplier ships it and this row tracks what they say they hold. 'virtual' — a bucket that is not a building (pre-orders, consignment, a quarantine shelf). Descriptive only: sourcing order comes from `priority`, and no route in this app treats one type differently from another. Defaults to 'warehouse'.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/inventories/locations/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        api_params['address'] = self._normalize_value(address)
        if code is not None:
            api_params['code'] = self._normalize_value(code)
        if enabled is not None:
            api_params['enabled'] = self._normalize_value(enabled)
        api_params['labels'] = self._normalize_value(labels)
        api_params['metadata'] = self._normalize_value(metadata)
        if name is not None:
            api_params['name'] = self._normalize_value(name)
        if priority is not None:
            api_params['priority'] = self._normalize_value(priority)
        if type is not None:
            api_params['type'] = self._normalize_value(type)

        response = self.client.call('put', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)

