from ..service import Service
from typing import Any, Dict, List, Optional, Union
from ..exception import RevenexxException
from ..utils.deprecated import deprecated
from ..enums.kind import Kind;
from ..enums.products_kind import ProductsKind;
from ..models.error import Error;

class Products(Service):

    def __init__(self, client) -> None:
        super(Products, self).__init__(client)

    def products_list(
        self,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        order: Optional[str] = None,
        id: Optional[str] = None,
        sku: Optional[str] = None,
        kind: Optional[Kind] = None,
        parent_id: Optional[str] = None,
        family_id: Optional[str] = None,
        family_variant_id: Optional[str] = None,
        enabled: Optional[bool] = None,
        tax_class: Optional[str] = None,
        attribute_values: Optional[str] = None,
        label: Optional[str] = None,
        quantified_associations: Optional[str] = None,
        completeness: Optional[str] = None,
        created_at: Optional[str] = None,
        updated_at: Optional[str] = None,
        deleted_at: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        The catalog itself. A product row carries only what every product has — SKU, kind, family, enabled, tax class — and everything the tenant modelled lives in the `attribute_values` jsonb document, keyed by attribute CODE inside one of four scope buckets (common, per locale, per channel, per channel and locale). `label` is a generated column, maintained by the database so a grid of twenty thousand rows can sort and filter on a name with no join. `kind` says where the row sits in the variant hierarchy: a `model` carries what its variants share and is never sold itself.
        
        Every column of `products` is an exact-match query parameter, `order` sorts by one column, and `limit`/`offset` page through `page.total`. A query key that is NOT a column is dropped rather than refused, and the `filter` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked, and soft-deleted products are included — filter on `deleted_at` to read the live catalog, or use `GET /products/grid`, which excludes them.

        Parameters
        ----------
        limit : Optional[float]
            Page size (default 50, max 200). A larger value is clamped rather than refused.
        offset : Optional[float]
            Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
        order : Optional[str]
            Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.
        id : Optional[str]
            Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
        sku : Optional[str]
            Exact match on `sku`. The merchant's own article number — unique per tenant, and the value every integration (ERP, shop, feed, price list) joins on. The one identifier a person types, and the fallback this app shows when the catalog holds no name.
        kind : Optional[Kind]
            Exact match on `kind`. Where the product sits in the variant hierarchy. 'simple' stands on its own. 'model' carries the values its variants share and is never sold itself. 'variant' carries the axis values and points at its model through `parent_id`.
        parent_id : Optional[str]
            Exact match on `parent_id`. The product MODEL this variant belongs to. Only a `variant` carries one. Deleting the model leaves its variants behind with a null parent rather than deleting them.
        family_id : Optional[str]
            Exact match on `family_id`. The family that decides which attributes this product HAS. Without one nothing is required, completeness cannot be computed and the display name never resolves — `POST /products/{id}/family` is the call that sets it and computes completeness in the same step.
        family_variant_id : Optional[str]
            Exact match on `family_variant_id`. Which variant structure of the family this product follows — the axes it splits on. Null on a simple product.
        enabled : Optional[bool]
            Exact match on `enabled`. Whether the product is offered. A create defaults it from the `new_products_enabled_by_default` tenant setting rather than blindly to true, so an import does not publish twenty thousand unfinished products the moment it lands. An explicit value in the body always wins.
        tax_class : Optional[str]
            Exact match on `tax_class`. The tax class key the prices app resolves a VAT rate from. Free text here — the vocabulary belongs to the app that prices, and `POST /products/batch` exists to hand exactly this column to it in bulk.
        attribute_values : Optional[str]
            Exact match on `attribute_values`. Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
        label : Optional[str]
            Exact match on `label`. The display name, maintained by the DATABASE so a grid of twenty thousand rows can sort and filter on a name with no join. It is the first of `attribute_values.common.name`, `…common.label`, the `de`/`en`/`de_DE`/`en_US` locale buckets, `…common.manufacturer_aid`, and finally the SKU — so a value is ALWAYS present, and a label equal to the SKU means the catalog holds no name for this product. A generated column: it cannot be written, and a create or update that names it has it dropped rather than refused. The family-aware answer, which can consult `families.label_attribute` and report where the name came from, is `POST /products/labels`.
        quantified_associations : Optional[str]
            Exact match on `quantified_associations`. The import-side mirror of associations that carry a quantity — a bundle, a bill of materials, a spare-parts set. NOTHING IN THIS APP READS OR WRITES IT: no route produces it, no route consumes it, and it is null on every product this app has created. The surface that IS served is relational — `product_associations`, whose `quantity` column holds the number, guarded by `association_types.is_quantified`. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
        completeness : Optional[str]
            Exact match on `completeness`. How much of what this product's family REQUIRES it actually carries — the number a merchandiser works down. `required` counts the attributes the family marks `is_required`, `filled` how many of those carry a value in ANY bucket, `ratio` is filled/required between 0 and 1 (a family that requires nothing is 1, not undefined), `missing` lists the codes with no value anywhere, sorted, and `computed_at` is when it was measured. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
        created_at : Optional[str]
            Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.
        updated_at : Optional[str]
            Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.
        deleted_at : Optional[str]
            Exact match on `deleted_at`. When the product was soft-deleted. `GET /products/grid` and every category-rule evaluation exclude a row that carries one; `GET /products` does NOT — filter on it to read the live catalog.
        
        Returns
        -------
        Dict[str, Any]
            API response as a dictionary
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products'
        api_params = {}

        if limit is not None:
            api_params['limit'] = self._normalize_value(limit)
        if offset is not None:
            api_params['offset'] = self._normalize_value(offset)
        if order is not None:
            api_params['order'] = self._normalize_value(order)
        if id is not None:
            api_params['id'] = self._normalize_value(id)
        if sku is not None:
            api_params['sku'] = self._normalize_value(sku)
        if kind is not None:
            api_params['kind'] = self._normalize_value(kind)
        if parent_id is not None:
            api_params['parent_id'] = self._normalize_value(parent_id)
        if family_id is not None:
            api_params['family_id'] = self._normalize_value(family_id)
        if family_variant_id is not None:
            api_params['family_variant_id'] = self._normalize_value(family_variant_id)
        if enabled is not None:
            api_params['enabled'] = self._normalize_value(enabled)
        if tax_class is not None:
            api_params['tax_class'] = self._normalize_value(tax_class)
        if attribute_values is not None:
            api_params['attribute_values'] = self._normalize_value(attribute_values)
        if label is not None:
            api_params['label'] = self._normalize_value(label)
        if quantified_associations is not None:
            api_params['quantified_associations'] = self._normalize_value(quantified_associations)
        if completeness is not None:
            api_params['completeness'] = self._normalize_value(completeness)
        if created_at is not None:
            api_params['created_at'] = self._normalize_value(created_at)
        if updated_at is not None:
            api_params['updated_at'] = self._normalize_value(updated_at)
        if deleted_at is not None:
            api_params['deleted_at'] = self._normalize_value(deleted_at)

        response = self.client.call('get', api_path, {
        }, api_params)

        return response


    def products_create(
        self,
        sku: str,
        attribute_values: Optional[Dict[str, Any]] = None,
        completeness: Optional[Dict[str, Any]] = None,
        deleted_at: Optional[str] = None,
        enabled: Optional[bool] = None,
        family_id: Optional[str] = None,
        family_variant_id: Optional[str] = None,
        kind: Optional[ProductsKind] = None,
        parent_id: Optional[str] = None,
        quantified_associations: Optional[Dict[str, Any]] = None,
        tax_class: Optional[str] = None
    ) -> Error:
        """
        Creates one product and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.
        
        The catalog itself. A product row carries only what every product has — SKU, kind, family, enabled, tax class — and everything the tenant modelled lives in the `attribute_values` jsonb document, keyed by attribute CODE inside one of four scope buckets (common, per locale, per channel, per channel and locale). `label` is a generated column, maintained by the database so a grid of twenty thousand rows can sort and filter on a name with no join. `kind` says where the row sits in the variant hierarchy: a `model` carries what its variants share and is never sold itself.
        
        `sku` is the only column the database refuses the row without; everything else has a default or is nullable. A second row with the same `sku` answers 409. This app owns the create: `enabled` defaults from the `new_products_enabled_by_default` tenant setting rather than blindly to true, so an import cannot publish twenty thousand unfinished products the moment it lands, and a product that names no family gets the `default_product_family` one. An explicit value in the body always wins over both.

        Parameters
        ----------
        sku : str
            The merchant's own article number — unique per tenant, and the value every integration (ERP, shop, feed, price list) joins on. The one identifier a person types, and the fallback this app shows when the catalog holds no name.
        attribute_values : Optional[Dict[str, Any]]
            Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.
            
            Four buckets, and an attribute's own flags decide which one it writes to:
            
              `common`                    the attribute is neither localizable nor scopable — one value, full stop.
                                          `{"common": {"net_weight": 2.4, "colour": "black"}}`
              `locale_specific`           `localizable`: one value per language tag.
                                          `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
              `channel_specific`          `scopable`: one value per channel.
                                          `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
              `channel_locale_specific`   both: one value per channel AND language tag.
                                          `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`
            
            A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.
            
            The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.
            
            Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.
        completeness : Optional[Dict[str, Any]]
            How much of what this product's family REQUIRES it actually carries — the number a merchandiser works down. `required` counts the attributes the family marks `is_required`, `filled` how many of those carry a value in ANY bucket, `ratio` is filled/required between 0 and 1 (a family that requires nothing is 1, not undefined), `missing` lists the codes with no value anywhere, sorted, and `computed_at` is when it was measured.
            
            Written only by `POST /products/{id}/completeness` and by `POST /products/{id}/family`; a plain create or update never touches it, so it is null until one of the two has run. It also stays null for a product with no family — there is nothing to measure it against, and 0 % would be a lie.
        deleted_at : Optional[str]
            When the product was soft-deleted. `GET /products/grid` and every category-rule evaluation exclude a row that carries one; `GET /products` does NOT — filter on it to read the live catalog.
        enabled : Optional[bool]
            Whether the product is offered. A create defaults it from the `new_products_enabled_by_default` tenant setting rather than blindly to true, so an import does not publish twenty thousand unfinished products the moment it lands. An explicit value in the body always wins.
        family_id : Optional[str]
            The family that decides which attributes this product HAS. Without one nothing is required, completeness cannot be computed and the display name never resolves — `POST /products/{id}/family` is the call that sets it and computes completeness in the same step.
        family_variant_id : Optional[str]
            Which variant structure of the family this product follows — the axes it splits on. Null on a simple product.
        kind : Optional[ProductsKind]
            Where the product sits in the variant hierarchy. 'simple' stands on its own. 'model' carries the values its variants share and is never sold itself. 'variant' carries the axis values and points at its model through `parent_id`.
        parent_id : Optional[str]
            The product MODEL this variant belongs to. Only a `variant` carries one. Deleting the model leaves its variants behind with a null parent rather than deleting them.
        quantified_associations : Optional[Dict[str, Any]]
            The import-side mirror of associations that carry a quantity — a bundle, a bill of materials, a spare-parts set. NOTHING IN THIS APP READS OR WRITES IT: no route produces it, no route consumes it, and it is null on every product this app has created. The surface that IS served is relational — `product_associations`, whose `quantity` column holds the number, guarded by `association_types.is_quantified`.
            
            It exists because a PIM import (Akeneo, BMEcat) carries these in one blob keyed by association type code, and the column lets that document round-trip instead of being dropped. The database enforces no shape on it, so what a reader finds is whatever the importer wrote; the example is the conventional form.
        tax_class : Optional[str]
            The tax class key the prices app resolves a VAT rate from. Free text here — the vocabulary belongs to the app that prices, and `POST /products/batch` exists to hand exactly this column to it in bulk.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products'
        api_params = {}
        if sku is None:
            raise RevenexxException('Missing required parameter: "sku"')


        if attribute_values is not None:
            api_params['attribute_values'] = self._normalize_value(attribute_values)
        api_params['completeness'] = self._normalize_value(completeness)
        api_params['deleted_at'] = self._normalize_value(deleted_at)
        if enabled is not None:
            api_params['enabled'] = self._normalize_value(enabled)
        api_params['family_id'] = self._normalize_value(family_id)
        api_params['family_variant_id'] = self._normalize_value(family_variant_id)
        if kind is not None:
            api_params['kind'] = self._normalize_value(kind)
        api_params['parent_id'] = self._normalize_value(parent_id)
        api_params['quantified_associations'] = self._normalize_value(quantified_associations)
        api_params['sku'] = self._normalize_value(sku)
        api_params['tax_class'] = self._normalize_value(tax_class)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_batch(
        self,
        ids: Optional[List[str]] = None,
        skus: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Answers four fields — id, sku, tax_class and the resolved display name — for a list of ids and/or SKUs in ONE call. It exists for the app on the other side of a product reference: the prices app holds SKUs and needs a tax class, a feed builder holds ids and needs names, and neither should page through the catalog or fire a request per line. Ask by either identifier or both; the two are unioned and a product named twice comes back once.
        
        It answers what it FOUND: an id or SKU that names nothing is simply absent from `items` rather than an error, so compare the length of what you sent with what came back if a miss matters. It is not a general product read — for the whole row use `GET /products/{id}`, and for a scannable list use `GET /products/grid`.

        Parameters
        ----------
        ids : Optional[List[str]]
            Product ids, when the caller already holds them.
        skus : Optional[List[str]]
            Product SKUs — the identifier a foreign system carries, which is why this route exists at all.
        
        Returns
        -------
        Dict[str, Any]
            API response as a dictionary
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/batch'
        api_params = {}

        if ids is not None:
            api_params['ids'] = self._normalize_value(ids)
        if skus is not None:
            api_params['skus'] = self._normalize_value(skus)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return response


    def products_grid(
        self,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        order: Optional[str] = None,
        q: Optional[str] = None,
        kind: Optional[Kind] = None,
        enabled: Optional[bool] = None,
        family_id: Optional[str] = None
    ) -> Error:
        """
        The list a merchant can actually scan, as opposed to `GET /products`, which answers SKUs and a jsonb blob. Every row arrives already flattened: its resolved display name and where that name came from, its family code, its stored completeness, and the value of every attribute the catalog marks `usable_in_grid` — no join, no second call. `q` is a case-insensitive substring of the stored `label` column, which falls back to the SKU, so one box finds a product by either. Soft-deleted products are excluded here, unlike `GET /products`.
        
        It filters on `q`, `kind`, `enabled` and `family_id`, and on NOTHING ELSE — a query parameter it does not accept is refused with 400 rather than dropped. That matters because of `filters`: the array reports the attributes marked `is_filterable`, which is what a filter bar should OFFER, and it is not a query surface. Filtering on an attribute value is not offered by this API at all — the values live inside a four-bucket jsonb document and are read through a fallback chain, so it is a feature with a design of its own rather than a parameter that was forgotten.

        Parameters
        ----------
        limit : Optional[float]
            Page size (default 50, max 200). A larger value is clamped rather than refused.
        offset : Optional[float]
            Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
        order : Optional[str]
            Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.
        q : Optional[str]
            Case-insensitive substring of the display name (or the SKU, when there is no name).
        kind : Optional[Kind]
            Restrict to one product kind.
        enabled : Optional[bool]
            Restrict to enabled or disabled products.
        family_id : Optional[str]
            Restrict to one family. A family id that does not exist is not an error here — it simply matches nothing.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/grid'
        api_params = {}

        if limit is not None:
            api_params['limit'] = self._normalize_value(limit)
        if offset is not None:
            api_params['offset'] = self._normalize_value(offset)
        if order is not None:
            api_params['order'] = self._normalize_value(order)
        if q is not None:
            api_params['q'] = self._normalize_value(q)
        if kind is not None:
            api_params['kind'] = self._normalize_value(kind)
        if enabled is not None:
            api_params['enabled'] = self._normalize_value(enabled)
        if family_id is not None:
            api_params['family_id'] = self._normalize_value(family_id)

        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_labels(
        self,
        ids: Optional[List[str]] = None,
        skus: Optional[List[str]] = None
    ) -> Error:
        """
        What is this product CALLED? A product's name is an attribute rather than a column, and which attribute it is, is per family — so no plain read can answer it. This resolves up to 500 products at once, by id and/or SKU: it reads families.label_attribute (falling back to the default_label_attribute setting, then to the conventional `name`) and looks the value up through the scoped attribute_values document — common, then locale_specific in the label_locales order, then the channel buckets.
        
        It reports WHERE the name was found, which is the half that matters: `source: "sku"` means the catalog holds no name for this product and the SKU is standing in for one, so show it as a missing name rather than as a name. Writes nothing, and answers only what it found.

        Parameters
        ----------
        ids : Optional[List[str]]
            Product ids to name. At most 500.
        skus : Optional[List[str]]
            Product SKUs to name. At most 500.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/labels'
        api_params = {}

        if ids is not None:
            api_params['ids'] = self._normalize_value(ids)
        if skus is not None:
            api_params['skus'] = self._normalize_value(skus)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_product_associations_list(
        self,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        order: Optional[str] = None,
        id: Optional[str] = None,
        product_id: Optional[str] = None,
        association_type_id: Optional[str] = None,
        target_product_id: Optional[str] = None,
        quantity: Optional[float] = None,
        position: Optional[float] = None,
        created_at: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        One relation from one product to another, of a declared type: this drill's accessories, this bundle's parts, this article's cross-sells. `quantity` is the number in "this bundle contains 4 casters" and is meaningful only when the association type carries `is_quantified`. This relational surface is the one this app serves; the `products.quantified_associations` column is an importer's blob that no route here reads or writes.
        
        Every column of `product_associations` is an exact-match query parameter, `order` sorts by one column, and `limit`/`offset` page through `page.total`. A query key that is NOT a column is dropped rather than refused, and the `filter` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        limit : Optional[float]
            Page size (default 50, max 200). A larger value is clamped rather than refused.
        offset : Optional[float]
            Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
        order : Optional[str]
            Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.
        id : Optional[str]
            Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
        product_id : Optional[str]
            Exact match on `product_id`. The product the relation starts at — the one whose detail page shows it.
        association_type_id : Optional[str]
            Exact match on `association_type_id`. Which kind of relation this is — the `association_types` row.
        target_product_id : Optional[str]
            Exact match on `target_product_id`. The product the relation points at — the accessory, the spare part, the cross-sell.
        quantity : Optional[float]
            Exact match on `quantity`. How many of the target belong to the source — the 4 in "this bundle contains 4 casters". Only meaningful when the association type carries `is_quantified`; null on an ordinary cross-sell.
        position : Optional[float]
            Exact match on `position`. Order in which the targets are shown, ascending.
        created_at : Optional[str]
            Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.
        
        Returns
        -------
        Dict[str, Any]
            API response as a dictionary
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/product_associations'
        api_params = {}

        if limit is not None:
            api_params['limit'] = self._normalize_value(limit)
        if offset is not None:
            api_params['offset'] = self._normalize_value(offset)
        if order is not None:
            api_params['order'] = self._normalize_value(order)
        if id is not None:
            api_params['id'] = self._normalize_value(id)
        if product_id is not None:
            api_params['product_id'] = self._normalize_value(product_id)
        if association_type_id is not None:
            api_params['association_type_id'] = self._normalize_value(association_type_id)
        if target_product_id is not None:
            api_params['target_product_id'] = self._normalize_value(target_product_id)
        if quantity is not None:
            api_params['quantity'] = self._normalize_value(quantity)
        if position is not None:
            api_params['position'] = self._normalize_value(position)
        if created_at is not None:
            api_params['created_at'] = self._normalize_value(created_at)

        response = self.client.call('get', api_path, {
        }, api_params)

        return response


    def products_product_associations_create(
        self,
        association_type_id: str,
        product_id: str,
        target_product_id: str,
        position: Optional[float] = None,
        quantity: Optional[float] = None
    ) -> Error:
        """
        Creates one product association and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.
        
        One relation from one product to another, of a declared type: this drill's accessories, this bundle's parts, this article's cross-sells. `quantity` is the number in "this bundle contains 4 casters" and is meaningful only when the association type carries `is_quantified`. This relational surface is the one this app serves; the `products.quantified_associations` column is an importer's blob that no route here reads or writes.
        
        `product_id`, `association_type_id`, `target_product_id` are the only columns the database refuses the row without; everything else has a default or is nullable. A second row with the same `product_id`, `association_type_id`, `target_product_id` answers 409.

        Parameters
        ----------
        association_type_id : str
            Which kind of relation this is — the `association_types` row.
        product_id : str
            The product the relation starts at — the one whose detail page shows it.
        target_product_id : str
            The product the relation points at — the accessory, the spare part, the cross-sell.
        position : Optional[float]
            Order in which the targets are shown, ascending.
        quantity : Optional[float]
            How many of the target belong to the source — the 4 in "this bundle contains 4 casters". Only meaningful when the association type carries `is_quantified`; null on an ordinary cross-sell.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/product_associations'
        api_params = {}
        if association_type_id is None:
            raise RevenexxException('Missing required parameter: "association_type_id"')

        if product_id is None:
            raise RevenexxException('Missing required parameter: "product_id"')

        if target_product_id is None:
            raise RevenexxException('Missing required parameter: "target_product_id"')


        api_params['association_type_id'] = self._normalize_value(association_type_id)
        if position is not None:
            api_params['position'] = self._normalize_value(position)
        api_params['product_id'] = self._normalize_value(product_id)
        api_params['quantity'] = self._normalize_value(quantity)
        api_params['target_product_id'] = self._normalize_value(target_product_id)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_product_associations_delete(
        self,
        id: str
    ) -> Error:
        """
        Deletes one product association by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.
        
        Nothing in this schema references it, so nothing else changes.
        
        An id no product association of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.

        Parameters
        ----------
        id : str
            The `product_associations` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/product_associations`. An id no product association of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/product_associations/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('delete', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_product_associations_get(
        self,
        id: str
    ) -> Error:
        """
        Reads one product association by its id — the whole row, every column, as it is stored.
        
        One relation from one product to another, of a declared type: this drill's accessories, this bundle's parts, this article's cross-sells. `quantity` is the number in "this bundle contains 4 casters" and is meaningful only when the association type carries `is_quantified`. This relational surface is the one this app serves; the `products.quantified_associations` column is an importer's blob that no route here reads or writes.
        
        An id no product association of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        id : str
            The `product_associations` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/product_associations`. An id no product association of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/product_associations/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_product_associations_update(
        self,
        id: str,
        association_type_id: Optional[str] = None,
        position: Optional[float] = None,
        product_id: Optional[str] = None,
        quantity: Optional[float] = None,
        target_product_id: Optional[str] = None
    ) -> Error:
        """
        Updates one product association by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.
        
        One relation from one product to another, of a declared type: this drill's accessories, this bundle's parts, this article's cross-sells. `quantity` is the number in "this bundle contains 4 casters" and is meaningful only when the association type carries `is_quantified`. This relational surface is the one this app serves; the `products.quantified_associations` column is an importer's blob that no route here reads or writes.
        
        A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on `product_id`, `association_type_id`, `target_product_id` answers 409.

        Parameters
        ----------
        id : str
            The `product_associations` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/product_associations`. An id no product association of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        association_type_id : Optional[str]
            Which kind of relation this is — the `association_types` row.
        position : Optional[float]
            Order in which the targets are shown, ascending.
        product_id : Optional[str]
            The product the relation starts at — the one whose detail page shows it.
        quantity : Optional[float]
            How many of the target belong to the source — the 4 in "this bundle contains 4 casters". Only meaningful when the association type carries `is_quantified`; null on an ordinary cross-sell.
        target_product_id : Optional[str]
            The product the relation points at — the accessory, the spare part, the cross-sell.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/product_associations/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        if association_type_id is not None:
            api_params['association_type_id'] = self._normalize_value(association_type_id)
        if position is not None:
            api_params['position'] = self._normalize_value(position)
        if product_id is not None:
            api_params['product_id'] = self._normalize_value(product_id)
        api_params['quantity'] = self._normalize_value(quantity)
        if target_product_id is not None:
            api_params['target_product_id'] = self._normalize_value(target_product_id)

        response = self.client.call('put', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_vocabularies_list(
        self
    ) -> Dict[str, Any]:
        """
        The index of the enums this app ENFORCES — `product-kinds`, `membership-sources`, `rule-matches`, `asset-sources` — served by the app that owns the CHECK constraint each one is parsed out of, so a UI never has to keep its own copy of a status map and watch it drift. Names and titles only: fetch one by name for its values, badge tones and descriptions.
        
        The set is a fixed property of this app rather than tenant data, so it is the same list for every tenant. `attributes.type` is deliberately absent: it carries no CHECK, because the whole point of an attribute-driven PIM is that the type list is data an integrator extends.

        Returns
        -------
        Dict[str, Any]
            API response as a dictionary
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/vocabularies'
        api_params = {}

        response = self.client.call('get', api_path, {
        }, api_params)

        return response


    def products_vocabularies_get(
        self,
        name: str
    ) -> Error:
        """
        One vocabulary with every value it admits, each with a title, a description and the badge tone a UI should paint it in. The value set is parsed out of the CHECK constraint in schema.json, so what is served IS what is enforced. Labels are curated on top and can only add words and colour — a permitted value nobody labelled still appears, titled from its own key.

        Parameters
        ----------
        name : str
            The vocabulary name, as listed by GET /products/vocabularies.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/vocabularies/{name}'
        api_params = {}
        if name is None:
            raise RevenexxException('Missing required parameter: "name"')

        api_path = api_path.replace('{name}', str(self._normalize_value(name)))


        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_delete(
        self,
        id: str
    ) -> Error:
        """
        Deletes one product by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.
        
        It takes what hangs off it: product category memberships (`product_id`), product associations (`product_id` and `target_product_id`) are deleted with it. `products.parent_id` is set to null instead, so the rows that pointed at it survive the delete rather than going with it.
        
        An id no product of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one. `products.deleted_at` is a SOFT-delete marker that the grid and every category-rule evaluation honour, but no route in this app ever writes it — to soft-delete instead, `PUT /products/{id}` with a `deleted_at`.

        Parameters
        ----------
        id : str
            The `products` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products`. An id no product of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('delete', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_get(
        self,
        id: str
    ) -> Error:
        """
        Reads one product by its id — the whole row, every column, as it is stored.
        
        The catalog itself. A product row carries only what every product has — SKU, kind, family, enabled, tax class — and everything the tenant modelled lives in the `attribute_values` jsonb document, keyed by attribute CODE inside one of four scope buckets (common, per locale, per channel, per channel and locale). `label` is a generated column, maintained by the database so a grid of twenty thousand rows can sort and filter on a name with no join. `kind` says where the row sits in the variant hierarchy: a `model` carries what its variants share and is never sold itself.
        
        An id no product of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached. Nothing is resolved for you here — for the display name, the family code and the grid attributes already unpacked, use `GET /products/grid` or `POST /products/labels`.

        Parameters
        ----------
        id : str
            The `products` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products`. An id no product of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_update(
        self,
        id: str,
        attribute_values: Optional[Dict[str, Any]] = None,
        completeness: Optional[Dict[str, Any]] = None,
        deleted_at: Optional[str] = None,
        enabled: Optional[bool] = None,
        family_id: Optional[str] = None,
        family_variant_id: Optional[str] = None,
        kind: Optional[ProductsKind] = None,
        parent_id: Optional[str] = None,
        quantified_associations: Optional[Dict[str, Any]] = None,
        sku: Optional[str] = None,
        tax_class: Optional[str] = None
    ) -> Error:
        """
        Updates one product by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.
        
        The catalog itself. A product row carries only what every product has — SKU, kind, family, enabled, tax class — and everything the tenant modelled lives in the `attribute_values` jsonb document, keyed by attribute CODE inside one of four scope buckets (common, per locale, per channel, per channel and locale). `label` is a generated column, maintained by the database so a grid of twenty thousand rows can sort and filter on a name with no join. `kind` says where the row sits in the variant hierarchy: a `model` carries what its variants share and is never sold itself.
        
        A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on `sku` answers 409. `label` is a generated column: naming it is dropped rather than refused, and `completeness` is written by the two metadata routes, not here.

        Parameters
        ----------
        id : str
            The `products` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products`. An id no product of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        attribute_values : Optional[Dict[str, Any]]
            Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.
            
            Four buckets, and an attribute's own flags decide which one it writes to:
            
              `common`                    the attribute is neither localizable nor scopable — one value, full stop.
                                          `{"common": {"net_weight": 2.4, "colour": "black"}}`
              `locale_specific`           `localizable`: one value per language tag.
                                          `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
              `channel_specific`          `scopable`: one value per channel.
                                          `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
              `channel_locale_specific`   both: one value per channel AND language tag.
                                          `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`
            
            A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.
            
            The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.
            
            Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.
        completeness : Optional[Dict[str, Any]]
            How much of what this product's family REQUIRES it actually carries — the number a merchandiser works down. `required` counts the attributes the family marks `is_required`, `filled` how many of those carry a value in ANY bucket, `ratio` is filled/required between 0 and 1 (a family that requires nothing is 1, not undefined), `missing` lists the codes with no value anywhere, sorted, and `computed_at` is when it was measured.
            
            Written only by `POST /products/{id}/completeness` and by `POST /products/{id}/family`; a plain create or update never touches it, so it is null until one of the two has run. It also stays null for a product with no family — there is nothing to measure it against, and 0 % would be a lie.
        deleted_at : Optional[str]
            When the product was soft-deleted. `GET /products/grid` and every category-rule evaluation exclude a row that carries one; `GET /products` does NOT — filter on it to read the live catalog.
        enabled : Optional[bool]
            Whether the product is offered. A create defaults it from the `new_products_enabled_by_default` tenant setting rather than blindly to true, so an import does not publish twenty thousand unfinished products the moment it lands. An explicit value in the body always wins.
        family_id : Optional[str]
            The family that decides which attributes this product HAS. Without one nothing is required, completeness cannot be computed and the display name never resolves — `POST /products/{id}/family` is the call that sets it and computes completeness in the same step.
        family_variant_id : Optional[str]
            Which variant structure of the family this product follows — the axes it splits on. Null on a simple product.
        kind : Optional[ProductsKind]
            Where the product sits in the variant hierarchy. 'simple' stands on its own. 'model' carries the values its variants share and is never sold itself. 'variant' carries the axis values and points at its model through `parent_id`.
        parent_id : Optional[str]
            The product MODEL this variant belongs to. Only a `variant` carries one. Deleting the model leaves its variants behind with a null parent rather than deleting them.
        quantified_associations : Optional[Dict[str, Any]]
            The import-side mirror of associations that carry a quantity — a bundle, a bill of materials, a spare-parts set. NOTHING IN THIS APP READS OR WRITES IT: no route produces it, no route consumes it, and it is null on every product this app has created. The surface that IS served is relational — `product_associations`, whose `quantity` column holds the number, guarded by `association_types.is_quantified`.
            
            It exists because a PIM import (Akeneo, BMEcat) carries these in one blob keyed by association type code, and the column lets that document round-trip instead of being dropped. The database enforces no shape on it, so what a reader finds is whatever the importer wrote; the example is the conventional form.
        sku : Optional[str]
            The merchant's own article number — unique per tenant, and the value every integration (ERP, shop, feed, price list) joins on. The one identifier a person types, and the fallback this app shows when the catalog holds no name.
        tax_class : Optional[str]
            The tax class key the prices app resolves a VAT rate from. Free text here — the vocabulary belongs to the app that prices, and `POST /products/batch` exists to hand exactly this column to it in bulk.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        if attribute_values is not None:
            api_params['attribute_values'] = self._normalize_value(attribute_values)
        api_params['completeness'] = self._normalize_value(completeness)
        api_params['deleted_at'] = self._normalize_value(deleted_at)
        if enabled is not None:
            api_params['enabled'] = self._normalize_value(enabled)
        api_params['family_id'] = self._normalize_value(family_id)
        api_params['family_variant_id'] = self._normalize_value(family_variant_id)
        if kind is not None:
            api_params['kind'] = self._normalize_value(kind)
        api_params['parent_id'] = self._normalize_value(parent_id)
        api_params['quantified_associations'] = self._normalize_value(quantified_associations)
        if sku is not None:
            api_params['sku'] = self._normalize_value(sku)
        api_params['tax_class'] = self._normalize_value(tax_class)

        response = self.client.call('put', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_completeness(
        self,
        id: str,
        data: Dict[str, Any]
    ) -> Error:
        """
        How much of what its family REQUIRES does this product actually carry — the number a merchandiser works down. products.completeness is jsonb that nothing had ever written. This computes it from family_attributes (is_required) against the product's own scoped attribute_values and stores the result. A product with no family answers 400 rather than an invented 0 % — it has nothing to be measured against.

        Parameters
        ----------
        id : str
            The `products` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products`. An id no product of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        data : Dict[str, Any]
            Request body
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/{id}/completeness'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        if data is None:
            raise RevenexxException('Missing required parameter: "data"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        api_params['data'] = self._normalize_value(data)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_family_assign(
        self,
        id: str,
        family_code: Optional[str] = None,
        family_id: Optional[str] = None
    ) -> Error:
        """
        Names the family in the body — by `family_id` or by `family_code`, whichever the caller holds — and computes the product's completeness in the same call. The step every family-driven surface waits on: a product with no family has no required attributes, so its completeness cannot be computed and its family's label attribute never resolves. Assigning the family recomputes and STORES products.completeness immediately, so the metadata cannot go stale between the two operations.

        Parameters
        ----------
        id : str
            The `products` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products`. An id no product of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        family_code : Optional[str]
            Alternative to family_id — a `families.code` this tenant holds, from `GET /products/families`. No example: a code is tenant data, and any value published here names a family somebody does not have.
        family_id : Optional[str]
            The family to assign.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/{id}/family'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        if family_code is not None:
            api_params['family_code'] = self._normalize_value(family_code)
        if family_id is not None:
            api_params['family_id'] = self._normalize_value(family_id)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)

