from ..service import Service
from typing import Any, Dict, List, Optional, Union
from ..exception import RevenexxException
from ..utils.deprecated import deprecated
from ..enums.products_assets_list_source import ProductsAssetsListSource;
from ..enums.assets_source import AssetsSource;
from ..models.error import Error;

class ProductsAssets(Service):

    def __init__(self, client) -> None:
        super(ProductsAssets, self).__init__(client)

    def products_assets_list(
        self,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        order: Optional[str] = None,
        id: Optional[str] = None,
        asset_family_id: Optional[str] = None,
        code: Optional[str] = None,
        source: Optional[ProductsAssetsListSource] = None,
        storage_asset_id: Optional[str] = None,
        delivery_path: Optional[str] = None,
        external_url: Optional[str] = None,
        attribute_values: Optional[str] = None,
        created_at: Optional[str] = None,
        updated_at: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
        
        Every column of `assets` is an exact-match query parameter, `order` sorts by one column, and `limit`/`offset` page through `page.total`. A query key that is NOT a column is dropped rather than refused, and the `filter` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        limit : Optional[float]
            Page size (default 50, max 200). A larger value is clamped rather than refused.
        offset : Optional[float]
            Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
        order : Optional[str]
            Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.
        id : Optional[str]
            Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
        asset_family_id : Optional[str]
            Exact match on `asset_family_id`. The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.
        code : Optional[str]
            Exact match on `code`. The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.
        source : Optional[ProductsAssetsListSource]
            Exact match on `source`. Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.
        storage_asset_id : Optional[str]
            Exact match on `storage_asset_id`. The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.
        delivery_path : Optional[str]
            Exact match on `delivery_path`. The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.
        external_url : Optional[str]
            Exact match on `external_url`. Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.
        attribute_values : Optional[str]
            Exact match on `attribute_values`. Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
        created_at : Optional[str]
            Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.
        updated_at : Optional[str]
            Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.
        
        Returns
        -------
        Dict[str, Any]
            API response as a dictionary
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/assets'
        api_params = {}

        if limit is not None:
            api_params['limit'] = self._normalize_value(limit)
        if offset is not None:
            api_params['offset'] = self._normalize_value(offset)
        if order is not None:
            api_params['order'] = self._normalize_value(order)
        if id is not None:
            api_params['id'] = self._normalize_value(id)
        if asset_family_id is not None:
            api_params['asset_family_id'] = self._normalize_value(asset_family_id)
        if code is not None:
            api_params['code'] = self._normalize_value(code)
        if source is not None:
            api_params['source'] = self._normalize_value(source)
        if storage_asset_id is not None:
            api_params['storage_asset_id'] = self._normalize_value(storage_asset_id)
        if delivery_path is not None:
            api_params['delivery_path'] = self._normalize_value(delivery_path)
        if external_url is not None:
            api_params['external_url'] = self._normalize_value(external_url)
        if attribute_values is not None:
            api_params['attribute_values'] = self._normalize_value(attribute_values)
        if created_at is not None:
            api_params['created_at'] = self._normalize_value(created_at)
        if updated_at is not None:
            api_params['updated_at'] = self._normalize_value(updated_at)

        response = self.client.call('get', api_path, {
        }, api_params)

        return response


    def products_assets_create(
        self,
        asset_family_id: str,
        code: str,
        attribute_values: Optional[Dict[str, Any]] = None,
        delivery_path: Optional[str] = None,
        external_url: Optional[str] = None,
        source: Optional[AssetsSource] = None,
        storage_asset_id: Optional[str] = None
    ) -> Error:
        """
        Creates one asset and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.
        
        One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
        
        `asset_family_id` and `code` are the only columns the database refuses the row without; everything else has a default or is nullable. A second row with the same `asset_family_id` and `code` answers 409. This app owns the create, because it is the only place an external URL can enter the catalog: an asset with no family falls back to the `default_asset_family` setting, and an `external` one is refused unless the tenant allows external media and the URL's host is on its allow-list.

        Parameters
        ----------
        asset_family_id : str
            The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.
        code : str
            The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.
        attribute_values : Optional[Dict[str, Any]]
            Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.
            
            Four buckets, and an attribute's own flags decide which one it writes to:
            
              `common`                    the attribute is neither localizable nor scopable — one value, full stop.
                                          `{"common": {"net_weight": 2.4, "colour": "black"}}`
              `locale_specific`           `localizable`: one value per language tag.
                                          `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
              `channel_specific`          `scopable`: one value per channel.
                                          `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
              `channel_locale_specific`   both: one value per channel AND language tag.
                                          `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`
            
            A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.
            
            The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.
            
            Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.
            
            Which attributes an asset of this family has comes from `attributes` rows with `entity_type: "asset"` and `entity_ref` equal to the family's code — alt text, copyright, an expiry date.
        delivery_path : Optional[str]
            The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.
        external_url : Optional[str]
            Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.
        source : Optional[AssetsSource]
            Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.
        storage_asset_id : Optional[str]
            The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/assets'
        api_params = {}
        if asset_family_id is None:
            raise RevenexxException('Missing required parameter: "asset_family_id"')

        if code is None:
            raise RevenexxException('Missing required parameter: "code"')


        api_params['asset_family_id'] = self._normalize_value(asset_family_id)
        if attribute_values is not None:
            api_params['attribute_values'] = self._normalize_value(attribute_values)
        api_params['code'] = self._normalize_value(code)
        api_params['delivery_path'] = self._normalize_value(delivery_path)
        api_params['external_url'] = self._normalize_value(external_url)
        if source is not None:
            api_params['source'] = self._normalize_value(source)
        api_params['storage_asset_id'] = self._normalize_value(storage_asset_id)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_assets_delete(
        self,
        id: str
    ) -> Error:
        """
        Deletes one asset by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.
        
        Nothing in this schema references it, so nothing else changes.
        
        An id no asset of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.

        Parameters
        ----------
        id : str
            The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/assets/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('delete', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_assets_get(
        self,
        id: str
    ) -> Error:
        """
        Reads one asset by its id — the whole row, every column, as it is stored.
        
        One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
        
        An id no asset of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        id : str
            The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/assets/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_assets_update(
        self,
        id: str,
        asset_family_id: Optional[str] = None,
        attribute_values: Optional[Dict[str, Any]] = None,
        code: Optional[str] = None,
        delivery_path: Optional[str] = None,
        external_url: Optional[str] = None,
        source: Optional[AssetsSource] = None,
        storage_asset_id: Optional[str] = None
    ) -> Error:
        """
        Updates one asset by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.
        
        One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (`source: "storage"` with a `storage_asset_id` that survives a rename) or on somebody else's host (`source: "external"` with an `external_url`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.
        
        A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on `asset_family_id` and `code` answers 409.

        Parameters
        ----------
        id : str
            The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        asset_family_id : Optional[str]
            The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.
        attribute_values : Optional[Dict[str, Any]]
            Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.
            
            Four buckets, and an attribute's own flags decide which one it writes to:
            
              `common`                    the attribute is neither localizable nor scopable — one value, full stop.
                                          `{"common": {"net_weight": 2.4, "colour": "black"}}`
              `locale_specific`           `localizable`: one value per language tag.
                                          `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
              `channel_specific`          `scopable`: one value per channel.
                                          `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
              `channel_locale_specific`   both: one value per channel AND language tag.
                                          `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`
            
            A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.
            
            The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.
            
            Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.
            
            Which attributes an asset of this family has comes from `attributes` rows with `entity_type: "asset"` and `entity_ref` equal to the family's code — alt text, copyright, an expiry date.
        code : Optional[str]
            The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.
        delivery_path : Optional[str]
            The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.
        external_url : Optional[str]
            Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.
        source : Optional[AssetsSource]
            Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.
        storage_asset_id : Optional[str]
            The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/assets/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        if asset_family_id is not None:
            api_params['asset_family_id'] = self._normalize_value(asset_family_id)
        if attribute_values is not None:
            api_params['attribute_values'] = self._normalize_value(attribute_values)
        if code is not None:
            api_params['code'] = self._normalize_value(code)
        api_params['delivery_path'] = self._normalize_value(delivery_path)
        api_params['external_url'] = self._normalize_value(external_url)
        if source is not None:
            api_params['source'] = self._normalize_value(source)
        api_params['storage_asset_id'] = self._normalize_value(storage_asset_id)

        response = self.client.call('put', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)

