from ..service import Service
from typing import Any, Dict, List, Optional, Union
from ..exception import RevenexxException
from ..utils.deprecated import deprecated
from ..models.error import Error;

class ProductsReferences(Service):

    def __init__(self, client) -> None:
        super(ProductsReferences, self).__init__(client)

    def products_reference_entities_list(
        self,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        order: Optional[str] = None,
        id: Optional[str] = None,
        code: Optional[str] = None,
        labels: Optional[str] = None,
        image: Optional[str] = None,
        created_at: Optional[str] = None,
        updated_at: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        A domain of records the catalog POINTS AT instead of duplicating — brands, manufacturers, care instructions. Declaring one is how a brand comes to be edited in one place rather than on nine thousand products. A reference entity has attributes of its own (`attributes` rows with `entity_type: "reference_entity"` and this entity's code as `entity_ref`), which is what makes its records more than a label.
        
        Every column of `reference_entities` is an exact-match query parameter, `order` sorts by one column, and `limit`/`offset` page through `page.total`. A query key that is NOT a column is dropped rather than refused, and the `filter` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        limit : Optional[float]
            Page size (default 50, max 200). A larger value is clamped rather than refused.
        offset : Optional[float]
            Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
        order : Optional[str]
            Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.
        id : Optional[str]
            Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
        code : Optional[str]
            Exact match on `code`. The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.
        labels : Optional[str]
            Exact match on `labels`. What the entity is called, per language tag — the heading over its record list. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
        image : Optional[str]
            Exact match on `image`. A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.
        created_at : Optional[str]
            Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.
        updated_at : Optional[str]
            Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.
        
        Returns
        -------
        Dict[str, Any]
            API response as a dictionary
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/reference_entities'
        api_params = {}

        if limit is not None:
            api_params['limit'] = self._normalize_value(limit)
        if offset is not None:
            api_params['offset'] = self._normalize_value(offset)
        if order is not None:
            api_params['order'] = self._normalize_value(order)
        if id is not None:
            api_params['id'] = self._normalize_value(id)
        if code is not None:
            api_params['code'] = self._normalize_value(code)
        if labels is not None:
            api_params['labels'] = self._normalize_value(labels)
        if image is not None:
            api_params['image'] = self._normalize_value(image)
        if created_at is not None:
            api_params['created_at'] = self._normalize_value(created_at)
        if updated_at is not None:
            api_params['updated_at'] = self._normalize_value(updated_at)

        response = self.client.call('get', api_path, {
        }, api_params)

        return response


    def products_reference_entities_create(
        self,
        code: str,
        image: Optional[str] = None,
        labels: Optional[Dict[str, Any]] = None
    ) -> Error:
        """
        Creates one reference entity and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.
        
        A domain of records the catalog POINTS AT instead of duplicating — brands, manufacturers, care instructions. Declaring one is how a brand comes to be edited in one place rather than on nine thousand products. A reference entity has attributes of its own (`attributes` rows with `entity_type: "reference_entity"` and this entity's code as `entity_ref`), which is what makes its records more than a label.
        
        `code` is the only column the database refuses the row without; everything else has a default or is nullable. A second row with the same `code` answers 409.

        Parameters
        ----------
        code : str
            The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.
        image : Optional[str]
            A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.
        labels : Optional[Dict[str, Any]]
            What the entity is called, per language tag — the heading over its record list.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/reference_entities'
        api_params = {}
        if code is None:
            raise RevenexxException('Missing required parameter: "code"')


        api_params['code'] = self._normalize_value(code)
        api_params['image'] = self._normalize_value(image)
        api_params['labels'] = self._normalize_value(labels)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_reference_entities_delete(
        self,
        id: str
    ) -> Error:
        """
        Deletes one reference entity by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.
        
        It takes what hangs off it: reference entity records (`reference_entity_id`) are deleted with it.
        
        An id no reference entity of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.

        Parameters
        ----------
        id : str
            The `reference_entities` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entities`. An id no reference entitie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/reference_entities/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('delete', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_reference_entities_get(
        self,
        id: str
    ) -> Error:
        """
        Reads one reference entity by its id — the whole row, every column, as it is stored.
        
        A domain of records the catalog POINTS AT instead of duplicating — brands, manufacturers, care instructions. Declaring one is how a brand comes to be edited in one place rather than on nine thousand products. A reference entity has attributes of its own (`attributes` rows with `entity_type: "reference_entity"` and this entity's code as `entity_ref`), which is what makes its records more than a label.
        
        An id no reference entity of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        id : str
            The `reference_entities` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entities`. An id no reference entitie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/reference_entities/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_reference_entities_update(
        self,
        id: str,
        code: Optional[str] = None,
        image: Optional[str] = None,
        labels: Optional[Dict[str, Any]] = None
    ) -> Error:
        """
        Updates one reference entity by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.
        
        A domain of records the catalog POINTS AT instead of duplicating — brands, manufacturers, care instructions. Declaring one is how a brand comes to be edited in one place rather than on nine thousand products. A reference entity has attributes of its own (`attributes` rows with `entity_type: "reference_entity"` and this entity's code as `entity_ref`), which is what makes its records more than a label.
        
        A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on `code` answers 409.

        Parameters
        ----------
        id : str
            The `reference_entities` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entities`. An id no reference entitie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        code : Optional[str]
            The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.
        image : Optional[str]
            A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.
        labels : Optional[Dict[str, Any]]
            What the entity is called, per language tag — the heading over its record list.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/reference_entities/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        if code is not None:
            api_params['code'] = self._normalize_value(code)
        api_params['image'] = self._normalize_value(image)
        api_params['labels'] = self._normalize_value(labels)

        response = self.client.call('put', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_reference_entity_records_list(
        self,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        order: Optional[str] = None,
        id: Optional[str] = None,
        reference_entity_id: Optional[str] = None,
        code: Optional[str] = None,
        labels: Optional[str] = None,
        attribute_values: Optional[str] = None,
        created_at: Optional[str] = None,
        updated_at: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        One record of a reference entity — one brand, one manufacturer. A product that points at it stores this record's CODE, exactly the way a select stores an option code, and the record's own properties live in its scoped `attribute_values` document. `GET /products/attribute-schema` offers these records as the `options` of any attribute that points at their entity, so a picker needs no second call.
        
        Every column of `reference_entity_records` is an exact-match query parameter, `order` sorts by one column, and `limit`/`offset` page through `page.total`. A query key that is NOT a column is dropped rather than refused, and the `filter` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        limit : Optional[float]
            Page size (default 50, max 200). A larger value is clamped rather than refused.
        offset : Optional[float]
            Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
        order : Optional[str]
            Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.
        id : Optional[str]
            Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
        reference_entity_id : Optional[str]
            Exact match on `reference_entity_id`. Which reference entity this record belongs to.
        code : Optional[str]
            Exact match on `code`. The record's stable identifier — the value a product stores when it points at this record, the same way a select stores an option code. Unique within the entity.
        labels : Optional[str]
            Exact match on `labels`. What the record is called, per language tag — the text a picker shows while the code is what gets written. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
        attribute_values : Optional[str]
            Exact match on `attribute_values`. Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
        created_at : Optional[str]
            Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.
        updated_at : Optional[str]
            Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.
        
        Returns
        -------
        Dict[str, Any]
            API response as a dictionary
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/reference_entity_records'
        api_params = {}

        if limit is not None:
            api_params['limit'] = self._normalize_value(limit)
        if offset is not None:
            api_params['offset'] = self._normalize_value(offset)
        if order is not None:
            api_params['order'] = self._normalize_value(order)
        if id is not None:
            api_params['id'] = self._normalize_value(id)
        if reference_entity_id is not None:
            api_params['reference_entity_id'] = self._normalize_value(reference_entity_id)
        if code is not None:
            api_params['code'] = self._normalize_value(code)
        if labels is not None:
            api_params['labels'] = self._normalize_value(labels)
        if attribute_values is not None:
            api_params['attribute_values'] = self._normalize_value(attribute_values)
        if created_at is not None:
            api_params['created_at'] = self._normalize_value(created_at)
        if updated_at is not None:
            api_params['updated_at'] = self._normalize_value(updated_at)

        response = self.client.call('get', api_path, {
        }, api_params)

        return response


    def products_reference_entity_records_create(
        self,
        code: str,
        reference_entity_id: str,
        attribute_values: Optional[Dict[str, Any]] = None,
        labels: Optional[Dict[str, Any]] = None
    ) -> Error:
        """
        Creates one reference entity record and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.
        
        One record of a reference entity — one brand, one manufacturer. A product that points at it stores this record's CODE, exactly the way a select stores an option code, and the record's own properties live in its scoped `attribute_values` document. `GET /products/attribute-schema` offers these records as the `options` of any attribute that points at their entity, so a picker needs no second call.
        
        `reference_entity_id` and `code` are the only columns the database refuses the row without; everything else has a default or is nullable. A second row with the same `reference_entity_id` and `code` answers 409.

        Parameters
        ----------
        code : str
            The record's stable identifier — the value a product stores when it points at this record, the same way a select stores an option code. Unique within the entity.
        reference_entity_id : str
            Which reference entity this record belongs to.
        attribute_values : Optional[Dict[str, Any]]
            Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.
            
            Four buckets, and an attribute's own flags decide which one it writes to:
            
              `common`                    the attribute is neither localizable nor scopable — one value, full stop.
                                          `{"common": {"net_weight": 2.4, "colour": "black"}}`
              `locale_specific`           `localizable`: one value per language tag.
                                          `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
              `channel_specific`          `scopable`: one value per channel.
                                          `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
              `channel_locale_specific`   both: one value per channel AND language tag.
                                          `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`
            
            A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.
            
            The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.
            
            Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.
            
            Which attributes a record of this entity has comes from `attributes` rows with `entity_type: "reference_entity"` and `entity_ref` equal to the entity's code — `GET /products/attribute-schema?entity_type=reference_entity&entity_ref=brand` answers it in one call.
        labels : Optional[Dict[str, Any]]
            What the record is called, per language tag — the text a picker shows while the code is what gets written.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/reference_entity_records'
        api_params = {}
        if code is None:
            raise RevenexxException('Missing required parameter: "code"')

        if reference_entity_id is None:
            raise RevenexxException('Missing required parameter: "reference_entity_id"')


        if attribute_values is not None:
            api_params['attribute_values'] = self._normalize_value(attribute_values)
        api_params['code'] = self._normalize_value(code)
        api_params['labels'] = self._normalize_value(labels)
        api_params['reference_entity_id'] = self._normalize_value(reference_entity_id)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_reference_entity_records_delete(
        self,
        id: str
    ) -> Error:
        """
        Deletes one reference entity record by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.
        
        Nothing in this schema references it, so nothing else changes.
        
        An id no reference entity record of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.

        Parameters
        ----------
        id : str
            The `reference_entity_records` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entity_records`. An id no reference entity record of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/reference_entity_records/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('delete', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_reference_entity_records_get(
        self,
        id: str
    ) -> Error:
        """
        Reads one reference entity record by its id — the whole row, every column, as it is stored.
        
        One record of a reference entity — one brand, one manufacturer. A product that points at it stores this record's CODE, exactly the way a select stores an option code, and the record's own properties live in its scoped `attribute_values` document. `GET /products/attribute-schema` offers these records as the `options` of any attribute that points at their entity, so a picker needs no second call.
        
        An id no reference entity record of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        id : str
            The `reference_entity_records` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entity_records`. An id no reference entity record of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/reference_entity_records/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_reference_entity_records_update(
        self,
        id: str,
        attribute_values: Optional[Dict[str, Any]] = None,
        code: Optional[str] = None,
        labels: Optional[Dict[str, Any]] = None,
        reference_entity_id: Optional[str] = None
    ) -> Error:
        """
        Updates one reference entity record by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.
        
        One record of a reference entity — one brand, one manufacturer. A product that points at it stores this record's CODE, exactly the way a select stores an option code, and the record's own properties live in its scoped `attribute_values` document. `GET /products/attribute-schema` offers these records as the `options` of any attribute that points at their entity, so a picker needs no second call.
        
        A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on `reference_entity_id` and `code` answers 409.

        Parameters
        ----------
        id : str
            The `reference_entity_records` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entity_records`. An id no reference entity record of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        attribute_values : Optional[Dict[str, Any]]
            Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.
            
            Four buckets, and an attribute's own flags decide which one it writes to:
            
              `common`                    the attribute is neither localizable nor scopable — one value, full stop.
                                          `{"common": {"net_weight": 2.4, "colour": "black"}}`
              `locale_specific`           `localizable`: one value per language tag.
                                          `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
              `channel_specific`          `scopable`: one value per channel.
                                          `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
              `channel_locale_specific`   both: one value per channel AND language tag.
                                          `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`
            
            A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.
            
            The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.
            
            Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.
            
            Which attributes a record of this entity has comes from `attributes` rows with `entity_type: "reference_entity"` and `entity_ref` equal to the entity's code — `GET /products/attribute-schema?entity_type=reference_entity&entity_ref=brand` answers it in one call.
        code : Optional[str]
            The record's stable identifier — the value a product stores when it points at this record, the same way a select stores an option code. Unique within the entity.
        labels : Optional[Dict[str, Any]]
            What the record is called, per language tag — the text a picker shows while the code is what gets written.
        reference_entity_id : Optional[str]
            Which reference entity this record belongs to.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/reference_entity_records/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        if attribute_values is not None:
            api_params['attribute_values'] = self._normalize_value(attribute_values)
        if code is not None:
            api_params['code'] = self._normalize_value(code)
        api_params['labels'] = self._normalize_value(labels)
        if reference_entity_id is not None:
            api_params['reference_entity_id'] = self._normalize_value(reference_entity_id)

        response = self.client.call('put', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)

