from ..service import Service
from typing import Any, Dict, List, Optional, Union
from ..exception import RevenexxException
from ..utils.deprecated import deprecated
from ..enums.rule_match import RuleMatch;
from ..enums.categories_rule_match import CategoriesRuleMatch;
from ..models.error import Error;
from ..models.category_rule_condition import CategoryRuleCondition;
from ..enums.category_rule_match import CategoryRuleMatch;
from ..enums.source import Source;
from ..enums.product_categories_source import ProductCategoriesSource;

class ProductsCategories(Service):

    def __init__(self, client) -> None:
        super(ProductsCategories, self).__init__(client)

    def products_categories_list(
        self,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        order: Optional[str] = None,
        id: Optional[str] = None,
        code: Optional[str] = None,
        parent_id: Optional[str] = None,
        path: Optional[str] = None,
        position: Optional[float] = None,
        labels: Optional[str] = None,
        values: Optional[str] = None,
        rules: Optional[str] = None,
        rule_match: Optional[RuleMatch] = None,
        rules_computed_at: Optional[str] = None,
        created_at: Optional[str] = None,
        updated_at: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        One node of the category tree. `parent_id` is the structure this app navigates — null is a root — while `path` is kept only for importers that carry one and nothing here reads or writes it. A category is hand-picked or RULE-DRIVEN: a non-null `rules` selector makes every matching product a `product_categories` row with source `rule`, alongside the hand-picked ones, and `rules_computed_at` says when that last completed.
        
        Every column of `categories` is an exact-match query parameter, `order` sorts by one column, and `limit`/`offset` page through `page.total`. A query key that is NOT a column is dropped rather than refused, and the `filter` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        limit : Optional[float]
            Page size (default 50, max 200). A larger value is clamped rather than refused.
        offset : Optional[float]
            Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
        order : Optional[str]
            Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.
        id : Optional[str]
            Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
        code : Optional[str]
            Exact match on `code`. The category's stable identifier — what an import and a storefront join on, and what survives a rename of the label. Unique per tenant.
        parent_id : Optional[str]
            Exact match on `parent_id`. The category this one hangs under. Null is a root of the tree. Deleting a parent lifts its children to the root rather than deleting them, so a mis-click never takes a subtree with it.
        path : Optional[str]
            Exact match on `path`. A materialized position in the tree, kept for importers that carry one (`tools/power_tools/cordless_drills`). Nothing in this app writes or reads it — `parent_id` is the structure this app navigates.
        position : Optional[float]
            Exact match on `position`. Order among the siblings under the same parent, ascending.
        labels : Optional[str]
            Exact match on `labels`. The category name a person sees, per language tag. The catalog reads by name, not by code — a locale left blank falls back to the next filled one. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
        values : Optional[str]
            Exact match on `values`. Whatever this catalog keeps on a category beyond the model — the keys belong to the tenant, not to this app, and nothing here reads them. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
        rules : Optional[str]
            Exact match on `rules`. The selector that makes this a RULE-DRIVEN category. Null means hand-picked. Matching products are MATERIALIZED as `product_categories` rows with source `rule`, next to the hand-picked ones a recompute never touches; `POST /products/categories/{category_id}/rules/preview` dry-runs this exact document before it is stored. Conditions address the `common` bucket of a product's values — a value held per locale or per channel has no single answer for a rule to test. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.
        rule_match : Optional[RuleMatch]
            Exact match on `rule_match`. How the conditions combine: 'all' ANDs them (the default), 'any' ORs them. It is a column of its own rather than a key of `rules` because the compiler reads the two separately.
        rules_computed_at : Optional[str]
            Exact match on `rules_computed_at`. When the rule last ran TO COMPLETION and its memberships were synced. Null means no pass has ever finished — a recompute is chunked, so a half-finished pass leaves this untouched.
        created_at : Optional[str]
            Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.
        updated_at : Optional[str]
            Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.
        
        Returns
        -------
        Dict[str, Any]
            API response as a dictionary
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/categories'
        api_params = {}

        if limit is not None:
            api_params['limit'] = self._normalize_value(limit)
        if offset is not None:
            api_params['offset'] = self._normalize_value(offset)
        if order is not None:
            api_params['order'] = self._normalize_value(order)
        if id is not None:
            api_params['id'] = self._normalize_value(id)
        if code is not None:
            api_params['code'] = self._normalize_value(code)
        if parent_id is not None:
            api_params['parent_id'] = self._normalize_value(parent_id)
        if path is not None:
            api_params['path'] = self._normalize_value(path)
        if position is not None:
            api_params['position'] = self._normalize_value(position)
        if labels is not None:
            api_params['labels'] = self._normalize_value(labels)
        if values is not None:
            api_params['values'] = self._normalize_value(values)
        if rules is not None:
            api_params['rules'] = self._normalize_value(rules)
        if rule_match is not None:
            api_params['rule_match'] = self._normalize_value(rule_match)
        if rules_computed_at is not None:
            api_params['rules_computed_at'] = self._normalize_value(rules_computed_at)
        if created_at is not None:
            api_params['created_at'] = self._normalize_value(created_at)
        if updated_at is not None:
            api_params['updated_at'] = self._normalize_value(updated_at)

        response = self.client.call('get', api_path, {
        }, api_params)

        return response


    def products_categories_create(
        self,
        code: str,
        labels: Optional[Dict[str, Any]] = None,
        parent_id: Optional[str] = None,
        path: Optional[str] = None,
        position: Optional[float] = None,
        rule_match: Optional[CategoriesRuleMatch] = None,
        rules: Optional[Dict[str, Any]] = None,
        rules_computed_at: Optional[str] = None,
        values: Optional[Dict[str, Any]] = None
    ) -> Error:
        """
        Creates one category and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.
        
        One node of the category tree. `parent_id` is the structure this app navigates — null is a root — while `path` is kept only for importers that carry one and nothing here reads or writes it. A category is hand-picked or RULE-DRIVEN: a non-null `rules` selector makes every matching product a `product_categories` row with source `rule`, alongside the hand-picked ones, and `rules_computed_at` says when that last completed.
        
        `code` is the only column the database refuses the row without; everything else has a default or is nullable. A second row with the same `code` answers 409.

        Parameters
        ----------
        code : str
            The category's stable identifier — what an import and a storefront join on, and what survives a rename of the label. Unique per tenant.
        labels : Optional[Dict[str, Any]]
            The category name a person sees, per language tag. The catalog reads by name, not by code — a locale left blank falls back to the next filled one.
        parent_id : Optional[str]
            The category this one hangs under. Null is a root of the tree. Deleting a parent lifts its children to the root rather than deleting them, so a mis-click never takes a subtree with it.
        path : Optional[str]
            A materialized position in the tree, kept for importers that carry one (`tools/power_tools/cordless_drills`). Nothing in this app writes or reads it — `parent_id` is the structure this app navigates.
        position : Optional[float]
            Order among the siblings under the same parent, ascending.
        rule_match : Optional[CategoriesRuleMatch]
            How the conditions combine: 'all' ANDs them (the default), 'any' ORs them. It is a column of its own rather than a key of `rules` because the compiler reads the two separately.
        rules : Optional[Dict[str, Any]]
            The selector that makes this a RULE-DRIVEN category. Null means hand-picked. Matching products are MATERIALIZED as `product_categories` rows with source `rule`, next to the hand-picked ones a recompute never touches; `POST /products/categories/{category_id}/rules/preview` dry-runs this exact document before it is stored. Conditions address the `common` bucket of a product's values — a value held per locale or per channel has no single answer for a rule to test.
        rules_computed_at : Optional[str]
            When the rule last ran TO COMPLETION and its memberships were synced. Null means no pass has ever finished — a recompute is chunked, so a half-finished pass leaves this untouched.
        values : Optional[Dict[str, Any]]
            Whatever this catalog keeps on a category beyond the model — the keys belong to the tenant, not to this app, and nothing here reads them.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/categories'
        api_params = {}
        if code is None:
            raise RevenexxException('Missing required parameter: "code"')


        api_params['code'] = self._normalize_value(code)
        api_params['labels'] = self._normalize_value(labels)
        api_params['parent_id'] = self._normalize_value(parent_id)
        api_params['path'] = self._normalize_value(path)
        if position is not None:
            api_params['position'] = self._normalize_value(position)
        api_params['rule_match'] = self._normalize_value(rule_match)
        api_params['rules'] = self._normalize_value(rules)
        api_params['rules_computed_at'] = self._normalize_value(rules_computed_at)
        api_params['values'] = self._normalize_value(values)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_categories_rules_recompute_all(
        self,
        data: Dict[str, Any]
    ) -> Error:
        """
        What the nightly `recompute-category-rules` schedule calls, and the call to reach for after a bulk import has changed what the rules select. Same sync as the single-category recompute, applied to every category with non-null rules. The whole run shares ONE budget: a category the budget no longer reaches is reported as `skipped` and picked up by the next run, and a failing category is reported in its result entry instead of aborting the run.

        Parameters
        ----------
        data : Dict[str, Any]
            Request body
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/categories/rules/recompute-all'
        api_params = {}
        if data is None:
            raise RevenexxException('Missing required parameter: "data"')


        api_params['data'] = self._normalize_value(data)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_categories_rules_preview(
        self,
        category_id: str,
        conditions: List[CategoryRuleCondition],
        rule_match: Optional[CategoryRuleMatch] = None
    ) -> Error:
        """
        Dry-runs a rule: how many products it selects, plus a sample of up to ten, and it WRITES NOTHING. Evaluates the rule in the request body against the live catalog WITHOUT touching product_categories — this powers the cockpit's "matches N products" preview while an operator edits a rule. Soft-deleted products are excluded. Counting is delegated to the database, never enumerated: a rule that compiles to a single query is answered by one exact-count request whatever its match set. A rule that needs several queries (rule_match "any", or a repeated column such as a range) is combined in the app and stops at `cap` ids — check `capped` before showing `count` as a total.

        Parameters
        ----------
        category_id : str
            The `categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/categories`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        conditions : List[CategoryRuleCondition]
            Between 1 and 25 conditions — a rule is a selector, not a query language. An empty list is a 400, not "everything".
        rule_match : Optional[CategoryRuleMatch]
            'all' ANDs every condition (default), 'any' ORs them.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/categories/{category_id}/rules/preview'
        api_params = {}
        if category_id is None:
            raise RevenexxException('Missing required parameter: "category_id"')

        if conditions is None:
            raise RevenexxException('Missing required parameter: "conditions"')

        api_path = api_path.replace('{category_id}', str(self._normalize_value(category_id)))

        api_params['conditions'] = self._normalize_value(conditions)
        api_params['rule_match'] = self._normalize_value(rule_match)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_categories_rules_recompute(
        self,
        category_id: str,
        cursor: Optional[str] = None
    ) -> Error:
        """
        Syncs one category's rule-derived memberships to what its stored rule selects today. Evaluates categories.rules (NOT the request body), then inserts the newly matching products as source='rule' rows and deletes the rule rows that no longer match. Manual (source='manual') memberships are never inserted, deleted or shadowed. Stamps categories.rules_computed_at.
        
        A large category does NOT finish in one call: the run stops when its wall-clock budget is spent and answers `done: false` with the `cursor` to send back, so drive it in a loop until `done` is true.

        Parameters
        ----------
        category_id : str
            The `categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/categories`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        cursor : Optional[str]
            The `cursor` a previous call returned, to continue that pass. Send `null` explicitly to restart from the beginning; omit the field to let the app decide (resume if a pass is in flight, otherwise start fresh). Anything that is not a string or null is a 400.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/categories/{category_id}/rules/recompute'
        api_params = {}
        if category_id is None:
            raise RevenexxException('Missing required parameter: "category_id"')

        api_path = api_path.replace('{category_id}', str(self._normalize_value(category_id)))

        api_params['cursor'] = self._normalize_value(cursor)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_categories_delete(
        self,
        id: str
    ) -> Error:
        """
        Deletes one category by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.
        
        It takes what hangs off it: product category memberships (`category_id`) are deleted with it. `categories.parent_id` is set to null instead, so the rows that pointed at it survive the delete rather than going with it.
        
        An id no category of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.

        Parameters
        ----------
        id : str
            The `categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/categories`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/categories/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('delete', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_categories_get(
        self,
        id: str
    ) -> Error:
        """
        Reads one category by its id — the whole row, every column, as it is stored.
        
        One node of the category tree. `parent_id` is the structure this app navigates — null is a root — while `path` is kept only for importers that carry one and nothing here reads or writes it. A category is hand-picked or RULE-DRIVEN: a non-null `rules` selector makes every matching product a `product_categories` row with source `rule`, alongside the hand-picked ones, and `rules_computed_at` says when that last completed.
        
        An id no category of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        id : str
            The `categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/categories`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/categories/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_categories_update(
        self,
        id: str,
        code: Optional[str] = None,
        labels: Optional[Dict[str, Any]] = None,
        parent_id: Optional[str] = None,
        path: Optional[str] = None,
        position: Optional[float] = None,
        rule_match: Optional[CategoriesRuleMatch] = None,
        rules: Optional[Dict[str, Any]] = None,
        rules_computed_at: Optional[str] = None,
        values: Optional[Dict[str, Any]] = None
    ) -> Error:
        """
        Updates one category by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.
        
        One node of the category tree. `parent_id` is the structure this app navigates — null is a root — while `path` is kept only for importers that carry one and nothing here reads or writes it. A category is hand-picked or RULE-DRIVEN: a non-null `rules` selector makes every matching product a `product_categories` row with source `rule`, alongside the hand-picked ones, and `rules_computed_at` says when that last completed.
        
        A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on `code` answers 409.

        Parameters
        ----------
        id : str
            The `categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/categories`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        code : Optional[str]
            The category's stable identifier — what an import and a storefront join on, and what survives a rename of the label. Unique per tenant.
        labels : Optional[Dict[str, Any]]
            The category name a person sees, per language tag. The catalog reads by name, not by code — a locale left blank falls back to the next filled one.
        parent_id : Optional[str]
            The category this one hangs under. Null is a root of the tree. Deleting a parent lifts its children to the root rather than deleting them, so a mis-click never takes a subtree with it.
        path : Optional[str]
            A materialized position in the tree, kept for importers that carry one (`tools/power_tools/cordless_drills`). Nothing in this app writes or reads it — `parent_id` is the structure this app navigates.
        position : Optional[float]
            Order among the siblings under the same parent, ascending.
        rule_match : Optional[CategoriesRuleMatch]
            How the conditions combine: 'all' ANDs them (the default), 'any' ORs them. It is a column of its own rather than a key of `rules` because the compiler reads the two separately.
        rules : Optional[Dict[str, Any]]
            The selector that makes this a RULE-DRIVEN category. Null means hand-picked. Matching products are MATERIALIZED as `product_categories` rows with source `rule`, next to the hand-picked ones a recompute never touches; `POST /products/categories/{category_id}/rules/preview` dry-runs this exact document before it is stored. Conditions address the `common` bucket of a product's values — a value held per locale or per channel has no single answer for a rule to test.
        rules_computed_at : Optional[str]
            When the rule last ran TO COMPLETION and its memberships were synced. Null means no pass has ever finished — a recompute is chunked, so a half-finished pass leaves this untouched.
        values : Optional[Dict[str, Any]]
            Whatever this catalog keeps on a category beyond the model — the keys belong to the tenant, not to this app, and nothing here reads them.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/categories/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        if code is not None:
            api_params['code'] = self._normalize_value(code)
        api_params['labels'] = self._normalize_value(labels)
        api_params['parent_id'] = self._normalize_value(parent_id)
        api_params['path'] = self._normalize_value(path)
        if position is not None:
            api_params['position'] = self._normalize_value(position)
        api_params['rule_match'] = self._normalize_value(rule_match)
        api_params['rules'] = self._normalize_value(rules)
        api_params['rules_computed_at'] = self._normalize_value(rules_computed_at)
        api_params['values'] = self._normalize_value(values)

        response = self.client.call('put', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_product_categories_list(
        self,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        order: Optional[str] = None,
        id: Optional[str] = None,
        product_id: Optional[str] = None,
        category_id: Optional[str] = None,
        position: Optional[float] = None,
        source: Optional[Source] = None,
        created_at: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        One membership: this product is filed in this category. `source` says how it got there — `manual` is hand-picked, `rule` was materialized by a category rule — and the two never touch each other: a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass. `POST /products/{id}/categories` is the friendlier way to create one, because it takes the product from the path and answers with the category code and the SKU.
        
        Every column of `product_categories` is an exact-match query parameter, `order` sorts by one column, and `limit`/`offset` page through `page.total`. A query key that is NOT a column is dropped rather than refused, and the `filter` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        limit : Optional[float]
            Page size (default 50, max 200). A larger value is clamped rather than refused.
        offset : Optional[float]
            Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.
        order : Optional[str]
            Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.
        id : Optional[str]
            Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
        product_id : Optional[str]
            Exact match on `product_id`. The product filed into the category. Deleting the product deletes the membership with it.
        category_id : Optional[str]
            Exact match on `category_id`. The category it is filed into. One row per (product, category), whichever way it got there.
        position : Optional[float]
            Exact match on `position`. Sort order of this product inside the category.
        source : Optional[Source]
            Exact match on `source`. How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass.
        created_at : Optional[str]
            Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.
        
        Returns
        -------
        Dict[str, Any]
            API response as a dictionary
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/product_categories'
        api_params = {}

        if limit is not None:
            api_params['limit'] = self._normalize_value(limit)
        if offset is not None:
            api_params['offset'] = self._normalize_value(offset)
        if order is not None:
            api_params['order'] = self._normalize_value(order)
        if id is not None:
            api_params['id'] = self._normalize_value(id)
        if product_id is not None:
            api_params['product_id'] = self._normalize_value(product_id)
        if category_id is not None:
            api_params['category_id'] = self._normalize_value(category_id)
        if position is not None:
            api_params['position'] = self._normalize_value(position)
        if source is not None:
            api_params['source'] = self._normalize_value(source)
        if created_at is not None:
            api_params['created_at'] = self._normalize_value(created_at)

        response = self.client.call('get', api_path, {
        }, api_params)

        return response


    def products_product_categories_create(
        self,
        category_id: str,
        product_id: str,
        position: Optional[float] = None,
        source: Optional[ProductCategoriesSource] = None
    ) -> Error:
        """
        Creates one product category membership and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.
        
        One membership: this product is filed in this category. `source` says how it got there — `manual` is hand-picked, `rule` was materialized by a category rule — and the two never touch each other: a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass. `POST /products/{id}/categories` is the friendlier way to create one, because it takes the product from the path and answers with the category code and the SKU.
        
        `product_id` and `category_id` are the only columns the database refuses the row without; everything else has a default or is nullable. A second row with the same `product_id` and `category_id` answers 409.

        Parameters
        ----------
        category_id : str
            The category it is filed into. One row per (product, category), whichever way it got there.
        product_id : str
            The product filed into the category. Deleting the product deletes the membership with it.
        position : Optional[float]
            Sort order of this product inside the category.
        source : Optional[ProductCategoriesSource]
            How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/product_categories'
        api_params = {}
        if category_id is None:
            raise RevenexxException('Missing required parameter: "category_id"')

        if product_id is None:
            raise RevenexxException('Missing required parameter: "product_id"')


        api_params['category_id'] = self._normalize_value(category_id)
        if position is not None:
            api_params['position'] = self._normalize_value(position)
        api_params['product_id'] = self._normalize_value(product_id)
        if source is not None:
            api_params['source'] = self._normalize_value(source)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_product_categories_delete(
        self,
        id: str
    ) -> Error:
        """
        Deletes one product category membership by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.
        
        Nothing in this schema references it, so nothing else changes.
        
        An id no product category membership of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.

        Parameters
        ----------
        id : str
            The `product_categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/product_categories`. An id no product categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/product_categories/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('delete', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_product_categories_get(
        self,
        id: str
    ) -> Error:
        """
        Reads one product category membership by its id — the whole row, every column, as it is stored.
        
        One membership: this product is filed in this category. `source` says how it got there — `manual` is hand-picked, `rule` was materialized by a category rule — and the two never touch each other: a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass. `POST /products/{id}/categories` is the friendlier way to create one, because it takes the product from the path and answers with the category code and the SKU.
        
        An id no product category membership of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.
        
        Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.

        Parameters
        ----------
        id : str
            The `product_categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/product_categories`. An id no product categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/product_categories/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))


        response = self.client.call('get', api_path, {
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_product_categories_update(
        self,
        id: str,
        category_id: Optional[str] = None,
        position: Optional[float] = None,
        product_id: Optional[str] = None,
        source: Optional[ProductCategoriesSource] = None
    ) -> Error:
        """
        Updates one product category membership by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.
        
        One membership: this product is filed in this category. `source` says how it got there — `manual` is hand-picked, `rule` was materialized by a category rule — and the two never touch each other: a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass. `POST /products/{id}/categories` is the friendlier way to create one, because it takes the product from the path and answers with the category code and the SKU.
        
        A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on `product_id` and `category_id` answers 409.

        Parameters
        ----------
        id : str
            The `product_categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/product_categories`. An id no product categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        category_id : Optional[str]
            The category it is filed into. One row per (product, category), whichever way it got there.
        position : Optional[float]
            Sort order of this product inside the category.
        product_id : Optional[str]
            The product filed into the category. Deleting the product deletes the membership with it.
        source : Optional[ProductCategoriesSource]
            How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/product_categories/{id}'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        if category_id is not None:
            api_params['category_id'] = self._normalize_value(category_id)
        if position is not None:
            api_params['position'] = self._normalize_value(position)
        if product_id is not None:
            api_params['product_id'] = self._normalize_value(product_id)
        if source is not None:
            api_params['source'] = self._normalize_value(source)

        response = self.client.call('put', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)


    def products_categories_assign(
        self,
        id: str,
        category_id: str,
        position: Optional[float] = None
    ) -> Error:
        """
        Files one product into one category by hand, and the membership is always `source: 'manual'` — a rule recompute never deletes or shadows it. product_categories holds 28 758 rows and had no write surface that named the product it was filing. This takes the product from the route and the category from the body, which is what a bulk 'add the selected products to …' needs. The membership is always source='manual', so a rule recompute never deletes or shadows it.

        Parameters
        ----------
        id : str
            The `products` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products`. An id no product of this tenant carries answers 404; a malformed one answers 400 before the route is reached.
        category_id : str
            The category to file the product into.
        position : Optional[float]
            Sort order inside the category. Default 0.
        
        Returns
        -------
        Error
            API response as a typed Pydantic model
        
        Raises
        ------
        RevenexxException
            If API request fails
        """

        api_path = '/v1/products/{id}/categories'
        api_params = {}
        if id is None:
            raise RevenexxException('Missing required parameter: "id"')

        if category_id is None:
            raise RevenexxException('Missing required parameter: "category_id"')

        api_path = api_path.replace('{id}', str(self._normalize_value(id)))

        api_params['category_id'] = self._normalize_value(category_id)
        if position is not None:
            api_params['position'] = self._normalize_value(position)

        response = self.client.call('post', api_path, {
            'content-type': 'application/json',
        }, api_params)

        return self._parse_response(response, model=Error)

